// Mi Cartera PRO V2 — backup and safe clients-only migration from V1.
(function(root){'use strict';
const K='mi-cartera-v2-validation-state';
const SNAP='mi-cartera-v2-before-client-migration';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clone=v=>JSON.parse(JSON.stringify(v));
function db(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return {}}}
function counts(d){return {clients:(d.clients||[]).length,credits:(d.credits||[]).length,payments:(d.payments||[]).length,cashMovements:(d.cashMovements||[]).length}}
function payload(){const d=db();return {app:'Mi Cartera PRO V2',schema:'v2-backup',version:2,exportedAt:new Date().toISOString(),counts:counts(d),db:d}}
function downloadObject(p,name){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function download(){downloadObject(payload(),'mi-cartera-pro-v2-backup-'+new Date().toISOString().slice(0,10)+'.json')}
function validateV2Backup(raw){if(!raw||raw.app!=='Mi Cartera PRO V2'||raw.schema!=='v2-backup'||Number(raw.version)!==2||!raw.db)throw new Error('El archivo no es un respaldo válido de Mi Cartera PRO V2.');const d=raw.db;for(const k of ['clients','credits','payments','cashMovements'])if(!Array.isArray(d[k]||[]))throw new Error('Respaldo V2 incompleto: '+k+'.');return {ok:true,counts:counts(d),db:clone(d)}}
function restoreV2(raw){const r=validateV2Backup(raw),before=payload();if(!confirm('Se reemplazará el estado local V2 por este respaldo. Se guardará primero una copia del estado actual. ¿Continuar?'))return false;localStorage.setItem('mi-cartera-v2-before-restore',JSON.stringify(before));localStorage.setItem(K,JSON.stringify(r.db));return true}
function inspectV2Restore(){const file=document.getElementById('v2RestoreFile')?.files?.[0];if(!file)return alert('Selecciona un respaldo V2.');const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result),r=validateV2Backup(raw);if(restoreV2(raw)){alert('Respaldo V2 restaurado correctamente. La aplicación se recargará.');location.reload()}}catch(e){alert(e.message)}};reader.readAsText(file)}
function cleanClient(x,i){
 const id=String(x?.id??'').trim()||`cli-v1-${i+1}`;
 return {id,name:String(x?.name||x?.nombre||'').trim(),phone:String(x?.phone||x?.telefono||'').trim(),dni:String(x?.dni||x?.document||x?.documento||'').trim(),address:String(x?.address||x?.direccion||'').trim(),guarantor:String(x?.guarantor||x?.fiador||'').trim(),guarantorPhone:String(x?.guarantorPhone||x?.telefonoFiador||'').trim(),reference:String(x?.reference||x?.referencia||'').trim(),route:String(x?.route||x?.routeId||x?.ruta||'').trim(),routeId:String(x?.routeId||x?.route||x?.ruta||'').trim(),location:String(x?.location||x?.ubicacion||'').trim(),version:1,migrationSource:'V1_CLIENTS_ONLY'};
}
function validate(raw){
 const source=raw?.db||raw;
 if(!source||!Array.isArray(source.clients))throw new Error('El archivo no contiene clientes de V1.');
 const errors=[],warnings=[],ids=new Set(),identity=new Set(),clients=[];
 source.clients.forEach((x,i)=>{const c=cleanClient(x,i),fingerprint=(c.dni||c.phone||c.name.toLowerCase());if(!c.name){errors.push(`Fila ${i+1}: falta el nombre`);return}if(ids.has(c.id)){errors.push(`ID duplicado: ${c.id}`);return}if(fingerprint&&identity.has(fingerprint)){warnings.push(`Posible cliente duplicado: ${c.name}`);return}ids.add(c.id);if(fingerprint)identity.add(fingerprint);clients.push(c)});
 return {ok:errors.length===0,clients,errors,warnings,sourceCount:source.clients.length,acceptedCount:clients.length,rejectedCount:source.clients.length-clients.length};
}
function report(r){const el=document.getElementById('clientMigrationReport');if(!el)return;el.innerHTML=`<div class="card"><b>${r.ok?'VALIDACIÓN APROBADA':'VALIDACIÓN BLOQUEADA'}</b><p>Encontrados: ${r.sourceCount} · Aceptados: ${r.acceptedCount} · Omitidos: ${r.rejectedCount}</p>${r.errors.length?`<p class="blocked">${r.errors.slice(0,30).map(esc).join('<br>')}</p>`:''}${r.warnings.length?`<p>${r.warnings.slice(0,30).map(esc).join('<br>')}</p>`:''}<p><b>No se copiarán créditos, pagos, saldos, caja, usuarios, caché ni configuraciones.</b></p><button class="btn green" id="applyClientMigration" ${r.ok?'':'disabled'}>Importar solamente clientes</button></div>`;const b=document.getElementById('applyClientMigration');if(b)b.onclick=()=>apply(r)}
function inspect(){const file=document.getElementById('v1ClientsFile')?.files?.[0];if(!file)return alert('Selecciona el respaldo JSON de V1.');const reader=new FileReader();reader.onload=()=>{try{const r=validate(JSON.parse(reader.result));root.__v2ClientMigration=r;report(r)}catch(e){alert(e.message)}};reader.readAsText(file)}
function apply(r){if(!r?.ok)return;if(!confirm(`Se importarán únicamente ${r.acceptedCount} clientes. ¿Continuar?`))return;const before=payload();localStorage.setItem(SNAP,JSON.stringify(before));downloadObject(before,'v2-antes-de-importar-clientes-'+new Date().toISOString().slice(0,10)+'.json');const current=db(),existing=Array.isArray(current.clients)?current.clients:[],byId=new Map(existing.map(x=>[String(x.id),x]));r.clients.forEach(c=>{if(!byId.has(String(c.id)))byId.set(String(c.id),c)});const next={...current,clients:[...byId.values()],credits:Array.isArray(current.credits)?current.credits:[],payments:Array.isArray(current.payments)?current.payments:[],cashMovements:Array.isArray(current.cashMovements)?current.cashMovements:[],audit:Array.isArray(current.audit)?current.audit:[],session:current.session||{actorId:'admin-local-v2',role:'admin'},clientMigration:{appliedAt:new Date().toISOString(),sourceCount:r.sourceCount,acceptedCount:r.acceptedCount}};localStorage.setItem(K,JSON.stringify(next));alert('Clientes importados correctamente. V2 se recargará.');location.reload()}
function rollback(){const raw=localStorage.getItem(SNAP);if(!raw)return alert('No existe un punto de reversión.');if(!confirm('¿Revertir la última importación de clientes?'))return;const p=JSON.parse(raw);if(!p?.db)return alert('El punto de reversión no es válido.');localStorage.setItem(K,JSON.stringify(p.db));alert('V2 volvió al estado anterior.');location.reload()}
function open(){document.getElementById('v2BackupPanel')?.remove();const p=payload(),has=!!localStorage.getItem(SNAP),el=document.createElement('div');el.id='v2BackupPanel';el.className='card';el.style='position:fixed;inset:4% 3%;z-index:9999;overflow:auto;background:#fff;padding:18px;box-shadow:0 10px 40px #0004';el.innerHTML=`<button class="btn" id="v2BackupClose">✕ Cerrar</button><h2>Respaldo e importación de clientes</h2><div class="card"><b>Estado actual V2</b><p>Clientes: ${p.counts.clients} · Créditos: ${p.counts.credits} · Pagos: ${p.counts.payments}</p><button class="btn blue" id="v2BackupDownload">Descargar respaldo V2</button><hr><b>Restaurar respaldo V2</b><p>Valida un respaldo de esta versión antes de reemplazar el estado local.</p><input id="v2RestoreFile" type="file" accept="application/json,.json" class="input"><button class="btn" id="v2RestoreApply">Validar y restaurar V2</button></div><div class="card"><b>Importar clientes desde V1</b><p>Selecciona el respaldo descargado desde V1. Primero se validará sin modificar V2.</p><input id="v1ClientsFile" type="file" accept="application/json,.json" class="input"><button class="btn blue" id="inspectV1Clients">Validar clientes</button><div id="clientMigrationReport"></div></div><div class="card"><b>Reversión</b><p>${has?'Existe un punto de restauración previo.':'Aún no se aplicó una importación.'}</p><button class="btn" id="rollbackClientMigration" ${has?'':'disabled'}>Revertir importación</button></div>`;document.body.appendChild(el);document.getElementById('v2BackupClose').onclick=()=>el.remove();document.getElementById('v2BackupDownload').onclick=download;document.getElementById('v2RestoreApply').onclick=inspectV2Restore;document.getElementById('inspectV1Clients').onclick=inspect;document.getElementById('rollbackClientMigration').onclick=rollback}
root.MiCarteraV2Backup={payload,download,open,validateV2Backup,restoreV2,inspectV2Restore,validate,inspect,apply,rollback};
})(window);
