// Mi Cartera PRO V2 — current backup and restoration.
(function(root){'use strict';
const K='mi-cartera-v2-validation-state';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const clone=v=>JSON.parse(JSON.stringify(v));
function db(){try{return JSON.parse(localStorage.getItem(K)||'{}')}catch{return {}}}
function counts(d){return {clients:(d.clients||[]).length,credits:(d.credits||[]).length,payments:(d.payments||[]).length,cashMovements:(d.cashMovements||[]).length}}
function journals(){const out={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(/^mi-cartera-v2-(cloud-operations|operations)(:|$)/.test(key))out[key]=localStorage.getItem(key)}return out}
function hasPending(journal){try{return Object.values(journal).some(raw=>{const rows=JSON.parse(raw);return !Array.isArray(rows)||rows.some(x=>x.status!=='SINCRONIZADO')})}catch{return true}}
function payload(){const d=db();return {app:'Mi Cartera PRO V2',schema:'v2-backup',version:2,exportedAt:new Date().toISOString(),counts:counts(d),db:d,localJournal:Object.fromEntries(Object.entries(journals()).filter(([key])=>key==='mi-cartera-v2-cloud-operations:'+root.MiCarteraV2AuthCloudGate?.state?.().uid)),localOwner:localStorage.getItem('mi-cartera-v2-local-owner')||''}}
function downloadObject(p,name){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function download(){const auth=root.MiCarteraV2AuthCloudGate?.state?.(),owner=localStorage.getItem('mi-cartera-v2-local-owner');if(!auth?.ready||!auth.uid||(owner&&owner!==auth.uid))return alert('Inicia sesión con la cuenta propietaria antes de descargar este respaldo.');downloadObject(payload(),'mi-cartera-pro-v2-backup-'+new Date().toISOString().slice(0,10)+'.json')}
function validateV2Backup(raw){if(!raw||raw.app!=='Mi Cartera PRO V2'||raw.schema!=='v2-backup'||Number(raw.version)!==2||!raw.db)throw new Error('El archivo no es un respaldo válido de Mi Cartera PRO V2.');const d=raw.db;for(const [k,label] of Object.entries({clients:'clientes',credits:'créditos',payments:'pagos',cashMovements:'movimientos de caja'}))if(!Array.isArray(d[k]||[]))throw new Error('Respaldo incompleto: '+label+'.');if(raw.localJournal)for(const [key,value] of Object.entries(raw.localJournal)){if(!/^mi-cartera-v2-(cloud-operations|operations)(:|$)/.test(key)||typeof value!=='string'||!Array.isArray(JSON.parse(value)))throw Error('El diario de sincronización del respaldo no es válido.')}return {ok:true,counts:counts(d),db:clone(d)}}
function restoreV2(raw){const auth=root.MiCarteraV2AuthCloudGate?.state?.(),owner=localStorage.getItem('mi-cartera-v2-local-owner');if(!auth?.ready||!auth.uid||(owner&&owner!==auth.uid)){alert('Inicia sesión con la cuenta propietaria antes de restaurar.');return false}const r=validateV2Backup(raw),before=payload();if(hasPending(journals())||hasPending(raw.localJournal||{})){alert('Hay operaciones pendientes. Conserva el respaldo y los datos actuales; consulta la sincronización antes de restaurar.');return false}if(!confirm('Se reemplazará el estado local por este respaldo. Se guardará primero una copia del estado actual. ¿Continuar?'))return false;localStorage.setItem('mi-cartera-v2-before-restore',JSON.stringify(before));localStorage.setItem(K,JSON.stringify(r.db));return true}
function inspectV2Restore(){const file=document.getElementById('v2RestoreFile')?.files?.[0];if(!file)return alert('Selecciona un respaldo V2.');const reader=new FileReader();reader.onload=()=>{try{const raw=JSON.parse(reader.result),r=validateV2Backup(raw);if(restoreV2(raw)){alert('Respaldo V2 restaurado correctamente. La aplicación se recargará.');location.reload()}}catch(e){alert(e.message)}};reader.readAsText(file)}
function open(){const auth=root.MiCarteraV2AuthCloudGate?.state?.(),owner=localStorage.getItem('mi-cartera-v2-local-owner');if(!auth?.ready||!auth.uid||(owner&&owner!==auth.uid))return alert('Inicia sesión con la cuenta propietaria para consultar el respaldo.');document.getElementById('v2BackupPanel')?.remove();const p=payload(),el=document.createElement('div');el.id='v2BackupPanel';el.className='card';el.style='position:fixed;inset:4% 3%;z-index:9999;overflow:auto;background:#fff;padding:18px;box-shadow:0 10px 40px #0004';el.innerHTML=`<button class="btn" id="v2BackupClose">✕ Cerrar</button><h2>Respaldo y restauración</h2><div class="card"><b>Estado actual</b><p>Clientes: ${p.counts.clients} · Créditos: ${p.counts.credits} · Pagos: ${p.counts.payments}</p><button class="btn blue" id="v2BackupDownload">Descargar respaldo</button><hr><b>Restaurar respaldo</b><p>Valida un respaldo de esta aplicación antes de reemplazar el estado local. Se conserva una copia previa.</p><input id="v2RestoreFile" type="file" accept="application/json,.json" class="input"><button class="btn" id="v2RestoreApply">Validar y restaurar</button></div>`;document.body.appendChild(el);document.getElementById('v2BackupClose').onclick=()=>el.remove();document.getElementById('v2BackupDownload').onclick=download;document.getElementById('v2RestoreApply').onclick=inspectV2Restore}
root.addEventListener('v2-auth-cloud-state',()=>document.getElementById('v2BackupPanel')?.remove());
root.MiCarteraV2Backup={payload,download,open,validateV2Backup,restoreV2,inspectV2Restore};
})(window);
