// Mi Cartera PRO V2 — edit an existing client without replacing its linked credits.
(function(root){'use strict';
const K='mi-cartera-v2-validation-state';
const FIELDS=['fName','fPhone','fDni','fAddress','fGuarantor','fGuarantorPhone','fReference','fRoute','fLocation'];
const $=id=>document.getElementById(id);
const id=prefix=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
function notify(message){if(typeof root.alert==='function')root.alert(message);}
function load(){try{return JSON.parse(root.localStorage?.getItem(K)||'{}')}catch{return {}}}
function save(d){root.localStorage?.setItem(K,JSON.stringify(d));root.MiCarteraV2CreditFormParity?.refreshClientOptions?.();root.MiCarteraV2CreditFormParity?.updateClientTools?.();root.V2UI?.render?.();root.MiCarteraV2Cards?.render?.();root.MiCarteraV2AdminParity?.render?.()}
function form(){return $('clientForm')}
function setMode(editId){const section=form(),heading=section?.querySelector('h2'),button=$('saveClient');if(editId){if(section)section.dataset.editId=String(editId);if(heading)heading.textContent='Editar cliente';if(button)button.textContent='💾 Guardar cambios';}else{if(section)delete section.dataset.editId;if(heading)heading.textContent='Crear cliente';if(button)button.textContent='➡ Guardar y continuar';}}
function setCreateMode(){setMode('')}
function setField(field,value){const el=$(field);if(el)el.value=String(value??'')}
function openEdit(clientId){const d=load(),c=(d.clients||[]).find(x=>String(x.id)===String(clientId));if(!c)return notify('Cliente no encontrado.');setMode(c.id);for(const field of FIELDS)setField(field,c[field]);root.show?.('clientForm');setTimeout(()=>$('fName')?.focus(),0)}
function decorate(){const list=$('clientsList');if(!list)return;for(const card of list.querySelectorAll('[data-client-card]')){if(card.querySelector('.v2-edit-client-button'))continue;const clientId=card.dataset.clientId;if(!clientId)continue;let row=card.querySelector('.v2-client-actions');if(!row){row=card.querySelector('.row');if(!row){row=document.createElement('div');row.className='row';row.style.marginTop='8px';card.appendChild(row)}row.classList.add('v2-client-actions')}const button=document.createElement('button');button.type='button';button.className='btn v2-edit-client-button';button.textContent='✏️ Editar';button.addEventListener('click',()=>openEdit(clientId));row.appendChild(button)}}
function wrapCards(){const cards=root.MiCarteraV2Cards;if(!cards||cards.__v2ClientEditWrapped)return;if(typeof cards.render==='function'){const render=cards.render;cards.render=function(){const result=render.apply(this,arguments);setTimeout(decorate,0);return result}}cards.__v2ClientEditWrapped=true}
function bindCreate(){const buttons=[...document.querySelectorAll('button')].filter(button=>/crear cliente/i.test(String(button.textContent||'')));for(const button of buttons)if(!button.dataset.v2EditCreateBound){button.dataset.v2EditCreateBound='1';button.addEventListener('click',setCreateMode,true)}}
async function updateClient(){try{const d=load(),section=form(),clientId=section?.dataset.editId,current=(d.clients||[]).find(x=>String(x.id)===String(clientId));if(!current)throw new Error('CLIENT_NOT_FOUND');const auditApi=root.MiCarteraV2AccessAudit,gate=root.MiCarteraV2OperationCommitGate;if(!auditApi||!gate)throw new Error('V2_CLIENT_EDIT_NOT_READY');const role=String(d.session?.role||auditApi.ROLES.ADMIN).toUpperCase();auditApi.requirePermission(role,'CLIENT_WRITE');const name=String($('fName')?.value||'').trim(),phone=String($('fPhone')?.value||'').trim();if(!name||!phone)throw new Error('Nombre y teléfono son obligatorios.');const route=String($('fRoute')?.value||'').trim(),next={...current,id:current.id,name,phone,dni:String($('fDni')?.value||'').trim(),address:String($('fAddress')?.value||'').trim(),guarantor:String($('fGuarantor')?.value||'').trim(),guarantorPhone:String($('fGuarantorPhone')?.value||'').trim(),reference:String($('fReference')?.value||'').trim(),route,routeId:route,location:String($('fLocation')?.value||'').trim(),version:Number(current.version||1)+1},op=id('op'),audit=auditApi.event({id:id('audit'),actorId:d.session?.actorId||'admin-local-v2',role:d.session?.role||role,action:'CLIENT_UPDATED',entityType:'CLIENT',entityId:current.id,operationId:op,detail:{changed:['name','phone','dni','address','guarantor','guarantorPhone','reference','route','location'].filter(field=>String(current[field]??'')!==String(next[field]??''))}});await gate.submit({bridge:root.MiCarteraV2SyncBridge,versionGuard:root.MiCarteraV2VersionGuard,authGate:root.MiCarteraV2AuthCloudGate,operation:{operationId:op,type:'CLIENT_UPDATE',entities:[{collection:'clients',kind:'set',data:next}],audit},onStatus:status=>{const el=$('syncStatus');if(el)el.textContent=status}});const index=d.clients.findIndex(x=>String(x.id)===String(current.id));d.clients[index]=next;d.audit=Array.isArray(d.audit)?d.audit:[];d.audit.push(audit);save(d);setCreateMode();root.MiCarteraV2CustomerExperience?.resetClientForm?.();root.show?.('clients');notify('Cliente actualizado correctamente.')}catch(error){notify(String(error?.message||error||'No se pudo actualizar el cliente.'))}}
function bindSave(){const button=$('saveClient');if(!button||button.dataset.v2EditSaveBound)return;button.dataset.v2EditSaveBound='1';button.onclick=()=>form()?.dataset.editId?updateClient():root.MiCarteraV2DurableActions?.addClient?.()}
function install(){wrapCards();bindCreate();bindSave();decorate();setTimeout(decorate,0);const search=$('clientSearch');if(search&&!search.dataset.v2EditSearchBound){search.dataset.v2EditSearchBound='1';search.addEventListener('input',()=>setTimeout(decorate,0))}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
root.MiCarteraV2ClientEditor={openEdit,setCreateMode,updateClient,decorate,install};
})(window);
