(function(){
function safeDb(){try{return typeof db!=="undefined"?db:null}catch(e){return null}}
function openBackupPanel(){const old=document.getElementById("backupPanel");if(old){old.remove();return}const d=document.createElement("div");d.id="backupPanel";d.className="modal open";d.innerHTML='<div class="sheet"><button class="btn close" onclick="document.getElementById(\'backupPanel\').remove()">✕</button><div class="sectionTitle">Respaldo y recuperación</div><p class="small muted">Exporta tu información y restáurala en otro dispositivo.</p><div class="card"><b>Guardar respaldo</b><p class="small">Clientes, créditos, pagos, caja, rutas, usuarios y configuración.</p><button class="btn green wide" onclick="exportCarteraBackup()">⬇️ Descargar respaldo</button></div><div class="card"><b>Recuperar respaldo</b><input id="backupFile" type="file" accept="application/json,.json" class="input" style="margin-bottom:8px"><button class="btn blue wide" onclick="importCarteraBackup()">⬆️ Restaurar respaldo</button></div><div class="card"><b>Importante</b><div class="small">El respaldo reemplaza los datos locales. Si utilizas Cloud, primero verifica que estás restaurando la información correcta: este proceso restaura el dispositivo local y no modifica automáticamente la base Cloud.</div></div></div>';document.body.appendChild(d)}
function exportCarteraBackup(){const d=safeDb();if(!d)return toast("No se pudo leer la información");const payload={app:"Préstamo Ya",version:4,exportedAt:new Date().toISOString(),counts:{clients:(d.clients||[]).length,credits:(d.credits||[]).length,payments:(d.payments||[]).length,routes:(d.routes||[]).length},db:d};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="prestamo-ya-backup-"+(typeof today==='function'?today():new Date().toISOString().slice(0,10))+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Respaldo descargado correctamente")}
function importCarteraBackup(){const input=document.getElementById("backupFile"),file=input&&input.files&&input.files[0];if(!file)return toast("Selecciona un respaldo .json");const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p||!p.db||!Array.isArray(p.db.clients)||!Array.isArray(p.db.credits)||!Array.isArray(p.db.payments))throw new Error();const c=p.counts||{};const resumen=`Clientes: ${p.db.clients.length} · Créditos: ${p.db.credits.length} · Pagos: ${p.db.payments.length}${c.routes!=null?' · Rutas: '+c.routes:''}`;if(!confirm("Respaldo encontrado.\n"+resumen+"\n\nEsto reemplazará los datos locales actuales. En Cloud, no se modifica automáticamente la base central. ¿Continuar?"))return;const raw=JSON.stringify(p.db);localStorage.setItem("mi_cartera_pro_v21",raw);localStorage.setItem("mi_cartera_pro_v19",raw);location.reload()}catch(e){toast("Respaldo inválido o dañado")}};r.readAsText(file)}
function getClient(id){const d=safeDb();return d&&d.clients?d.clients.find(c=>String(c.id)===String(id)):null}
function parseClientCoords(c){const raw=String(c?.location||'').trim().replace(/[\[\]]/g,'');const a=raw.split(',').map(Number);return a.length===2&&a.every(Number.isFinite)&&Math.abs(a[0])<=90&&Math.abs(a[1])<=180?{lat:a[0],lon:a[1]}:null}
function wazeClient(id){const c=getClient(id);if(!c)return toast('Cliente no encontrado');const p=parseClientCoords(c),q=String(c.address||'').trim();if(!p&&!q)return toast('Este cliente no tiene dirección ni ubicación registrada');const u=p?'https://waze.com/ul?ll='+encodeURIComponent(p.lat+','+p.lon)+'&navigate=yes':'https://waze.com/ul?q='+encodeURIComponent(q)+'&navigate=yes';window.open(u,'_blank','noopener')}
function mapClient(id){const c=getClient(id);if(!c)return toast('Cliente no encontrado');const p=parseClientCoords(c),q=String(c.address||'').trim();if(!p&&!q)return toast('Este cliente no tiene dirección ni ubicación registrada');const u=p?'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.lat+','+p.lon):'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q);window.open(u,'_blank','noopener')}
function addNavButtons(container,clientId){const c=getClient(clientId);if(!c||!container||container.querySelector('.clientNavButtons'))return;const wrap=document.createElement('div');wrap.className='actionbar clientNavButtons';wrap.innerHTML='<button type="button" class="btn blue" onclick="mapClient('+JSON.stringify(clientId)+')">🗺️ Mapa</button><button type="button" class="btn green" onclick="wazeClient('+JSON.stringify(clientId)+')">🚗 Ir con Waze</button>';container.appendChild(wrap)}
function enhanceClientCards(){const d=safeDb();if(!d)return;document.querySelectorAll('#clientsList .card').forEach(card=>{const b=card.querySelector('b');if(!b)return;const c=(d.clients||[]).find(x=>String(x.name).trim()===String(b.textContent).trim());if(c)addNavButtons(card,c.id)})}
function enhanceCollectionCards(){const d=safeDb();if(!d)return;document.querySelectorAll('#collectionsList .card').forEach(card=>{const b=card.querySelector('b');if(!b)return;const c=(d.clients||[]).find(x=>String(x.name).trim()===String(b.textContent).trim());if(c)addNavButtons(card,c.id)})}
function enhanceRouteCards(){const d=safeDb();if(!d)return;document.querySelectorAll('#routesList .card').forEach(card=>{const text=card.textContent||'';const m=text.match(/📍\s*([^\n]+)/);if(!m)return;const route=(d.routes||[]).find(r=>String(r.name).trim()===String(m[1]).trim());if(!route)return;const clients=(d.clients||[]).filter(c=>c.routeId===route.id&&String(c.location||'').trim()!=='');if(!clients.length)return;const wrap=document.createElement('div');wrap.className='actionbar clientNavButtons';wrap.innerHTML='<button type="button" class="btn green" onclick="wazeRoute('+JSON.stringify(route.id)+')">🚗 Abrir primera ubicación en Waze</button>';card.appendChild(wrap)})}
function wazeRoute(rid){const d=safeDb();const clients=(d?.clients||[]).filter(c=>c.routeId===rid);const c=clients.find(x=>parseClientCoords(x)||String(x.address||'').trim());if(!c)return toast('La ruta no tiene clientes con ubicación');wazeClient(c.id)}
function installNavigationEnhancers(){if(window.__navigationEnhancers)return;window.__navigationEnhancers=true;window.mapClient=mapClient;window.wazeClient=wazeClient;window.wazeRoute=wazeRoute;let tries=0;const tick=()=>{if(typeof window.renderClients==='function'&&!window.__renderClientsNav){const raw=window.renderClients;window.renderClients=function(){const r=raw.apply(this,arguments);setTimeout(enhanceClientCards,30);return r};window.__renderClientsNav=true}if(typeof window.renderCollections==='function'&&!window.__renderCollectionsNav){const raw=window.renderCollections;window.renderCollections=function(){const r=raw.apply(this,arguments);setTimeout(enhanceCollectionCards,30);return r};window.__renderCollectionsNav=true}if(typeof window.renderRoutes==='function'&&!window.__renderRoutesNav){const raw=window.renderRoutes;window.renderRoutes=function(){const r=raw.apply(this,arguments);setTimeout(enhanceRouteCards,30);return r};window.__renderRoutesNav=true}if((window.__renderClientsNav&&window.__renderCollectionsNav&&window.__renderRoutesNav)||tries++>60){enhanceClientCards();enhanceCollectionCards();enhanceRouteCards();return}setTimeout(tick,250)};tick()}
window.openBackupPanel=openBackupPanel;window.exportCarteraBackup=exportCarteraBackup;window.importCarteraBackup=importCarteraBackup;window.addNavButtons=addNavButtons;installNavigationEnhancers();
})();
