// Renovación V2: selector robusto por cliente y saldo anterior editable.
(()=>{
  const $=id=>document.getElementById(id);
  const norm=s=>String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toLowerCase();
  const money=v=>typeof window.money==='function'?window.money(v):'S/ '+Number(v||0).toFixed(2);
  const remain=id=>{const cr=(db.credits||[]).find(x=>String(x.id)===String(id));if(!cr)return 0;try{return Math.max(0,Number(window.status(cr).remain||0))}catch(_){return Math.max(0,Number(cr.total||0)-Number(cr.paid||0))}};
  const client=()=>{const direct=window.__selectedClientForProposal||window.__finalRenewalState?.clientId;if(direct){const c=(db.clients||[]).find(x=>String(x.id)===String(direct));if(c)return c}const text=($('creditClientBox')?.innerText||'').trim();const name=text.split(/\n|\r/)[0].trim();if(!name)return null;const c=(db.clients||[]).find(x=>norm(x.name)===norm(name));if(c)window.__selectedClientForProposal=c.id;return c||null};
  const selected=()=>window.__finalRenewalState?.renewalId||$('renewalCreditSelect')?.value||null;
  const setState=id=>{if(window.__finalRenewalState){window.__finalRenewalState.renewalId=id||null;window.__finalRenewalState.clientId=client()?.id||window.__finalRenewalState.clientId||null}};
  const ensureBalance=()=>{const notice=$('renewalNotice'),box=$('finalRenewalBox');if(!box)return;let input=$('renewalBalanceInput');if(!input){const wrap=document.createElement('div');wrap.className='field';wrap.id='renewalBalanceWrap';wrap.innerHTML='<label><b>Saldo anterior a cancelar S/</b></label><input class="input" id="renewalBalanceInput" type="number" min="0" step="0.01" value="0.00"><div class="small muted">Se descuenta del nuevo capital y no se entrega nuevamente al cliente. Puedes modificarlo antes de confirmar.</div><div id="renewalBalanceResult" class="info" style="margin-top:8px;background:#fff7e8;border-left:4px solid var(--orange)"></div>';(notice||box).insertAdjacentElement('afterend',wrap);input=$('renewalBalanceInput');input.addEventListener('input',()=>{input.dataset.edited='1';renderSummary()})}return input};
  const fill=()=>{const sel=$('renewalCreditSelect');if(!sel)return;const c=client();if(!c)return;const list=(db.credits||[]).filter(x=>String(x.clientId)===String(c.id)&&!['Renovado','Cancelado','Cerrado','Liquidado'].includes(String(x.status||''))&&remain(x.id)>0.009);const cur=sel.value;sel.innerHTML='<option value="">No renovar · crédito nuevo</option>'+list.map(x=>`<option value="${String(x.id).replace(/\"/g,'&quot;')}">#${x.id} · Capital ${money(x.capital)} · Saldo pendiente: ${money(remain(x.id))}</option>`).join('');if(cur&&list.some(x=>String(x.id)===String(cur)))sel.value=cur;else if(window.__finalRenewalState?.renewalId&&list.some(x=>String(x.id)===String(window.__finalRenewalState.renewalId)))sel.value=String(window.__finalRenewalState.renewalId);setState(sel.value);syncBalance()};
  const syncBalance=()=>{const input=ensureBalance(),id=selected();if(!input)return;const value=id?remain(id):0;if(!input.dataset.edited)input.value=value.toFixed(2);const shown=Number(input.value||0);if($('renewalBalanceResult'))$('renewalBalanceResult').innerHTML=`Saldo anterior: <b>${money(shown)}</b>${id&&shown!==value?' · detectado automáticamente: '+money(value):''}`;if(window.__finalRenewalState)window.__finalRenewalState.manualRenewalBalance=shown;renderSummary()};
  const renderSummary=()=>{const el=$('finalRenewalSummary'),id=selected();if(!el||!id)return;if(typeof window.__finalRenewalState!=='object')return;const cr=(db.credits||[]).find(x=>String(x.id)===String(id));if(!cr)return;const cap=Number($('cCapital')?.value||0),rate=Number($('cRate')?.value||0),term=Number($('cTerm')?.value||0),old=Number($('renewalBalanceInput')?.value||remain(id)),total=cap+cap*rate/100,delivery=cap-old,inst=term?total/term:0;el.innerHTML=`<div class="card"><b>Resumen de renovación</b><div class="grid"><div class="card metric">Saldo anterior<b>${money(old)}</b></div><div class="card metric">Nuevo capital<b>${money(cap)}</b></div><div class="card metric">Dinero a entregar<b>${money(Math.max(0,delivery))}</b></div><div class="card metric">Total nuevo<b>${money(total)}</b></div><div class="card metric">Cuota<b>${money(inst)}</b></div></div><div class="info">${money(cap)} − ${money(old)} = <b>${money(Math.max(0,delivery))}</b> entregados al cliente.</div></div>`};
  let lastClientId=null;
  const wire=()=>{const sel=$('renewalCreditSelect');const c=client();if(!sel)return;if(c&&String(c.id)!==String(lastClientId)){lastClientId=c.id;fill()}if(sel&&!sel.__renewalV2){sel.__renewalV2=true;sel.addEventListener('change',()=>{setState(sel.value||null);if(window.__finalRenewalState)window.__finalRenewalState.clientId=client()?.id||null;const input=ensureBalance();if(input)delete input.dataset.edited;setTimeout(()=>{syncBalance();if(typeof window.applyRenewalFields==='function'){try{window.applyRenewalFields()}catch(_){}}},20)})}ensureBalance();syncBalance()};
  const start=()=>{if($('creditForm'))wire();setTimeout(start,1000)};start();
  window.__prestamoYaRenewalFormV2=true;
})();
