// Renovación: el saldo pendiente se aplica al nuevo capital y solo se entrega la diferencia.
(()=>{
 const $=id=>document.getElementById(id),money=v=>'S/ '+Number(v||0).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2}),fmtDate=s=>{if(!s)return '-';const [y,m,d]=String(s).split('-');return d&&m&&y?`${d}/${m}/${y}`:s},esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
 const wait=()=>{if(typeof window.showCredit!=='function'||!window.db)return setTimeout(wait,300);install()};
 function install(){if(window.__prestamoYaRenewal)return;window.__prestamoYaRenewal=true;const raw=window.showCredit;window.showCredit=(id)=>{const r=raw(id);setTimeout(()=>addButton(id),100);return r};window.openRenewal=openRenewal;window.previewRenewal=previewRenewal;window.confirmRenewal=confirmRenewal;window.cancelRenewal=cancelRenewal;}
 function addButton(id){const body=$('creditDetailBody');if(!body)return;const bar=body.querySelector('.actionbar');if(!bar)return;const old=[...bar.querySelectorAll('button')].find(b=>/refinanciar/i.test(b.textContent||''));if(old){old.textContent='🔄 Renovar préstamo';old.onclick=()=>openRenewal(id);old.className='btn orange'}else if(!bar.querySelector('#renewCreditBtn')){const b=document.createElement('button');b.id='renewCreditBtn';b.className='btn orange';b.textContent='🔄 Renovar préstamo';b.onclick=()=>openRenewal(id);bar.appendChild(b)}}
 function getCredit(id){return (db.credits||[]).find(x=>String(x.id)===String(id))}
 function getClient(cr){return (db.clients||[]).find(x=>String(x.id)===String(cr?.clientId))}
 function pending(cr){if(!cr)return 0;const schedule=Array.isArray(cr.schedule)?cr.schedule:[];return Math.max(0,Number(cr.total||0)-schedule.reduce((s,q)=>s+Number(q.paid||0),0))}
 function openRenewal(id){window.__renewingCreditId=id;const old=getCredit(id);if(!old)return toast('No se encontró el crédito');const saldo=pending(old);if(saldo<=0)return toast('Este crédito no tiene saldo pendiente para renovar');const client=getClient(old),cap=Number(old.capital||0),rate=Number(old.rate||20),term=Number(old.term||4),freq=old.freq||'weekly';const modal=document.createElement('div');modal.id='renewalModal';modal.className='modal open';modal.innerHTML=`<div class="sheet"><button class="btn close" onclick="cancelRenewal()">✕</button><div class="sectionTitle">🔄 Renovación de préstamo</div><div class="card"><b>${esc(client?.name||'Cliente')}</b><div class="info">Crédito anterior #${esc(old.id)}</div><div class="info"><b>Saldo pendiente que se cancela:</b> ${money(saldo)}</div><div class="small muted">Este importe se aplica al nuevo préstamo y no se vuelve a entregar.</div></div><div class="card"><h3>Nuevo préstamo</h3><div class="twocol"><div class="field"><label>Nuevo capital S/</label><input class="input" id="rCapital" type="number" step="0.01" value="${cap}"></div><div class="field"><label>Interés %</label><input class="input" id="rRate" type="number" step="0.01" value="${rate}"></div></div><div class="twocol"><div class="field"><label>Plazo / cuotas</label><input class="input" id="rTerm" type="number" min="1" value="${term}"></div><div class="field"><label>Frecuencia</label><select class="select" id="rFreq"><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="monthly">Mensual</option></select></div></div><div class="twocol"><div class="field"><label>Fecha de renovación</label><input class="input" id="rDate" type="date" value="${today()}"></div><div class="field"><label>1ra fecha de pago</label><input class="input" id="rFirst" type="date" value="${old.first||today()}"></div></div><div class="grid"><div class="card metric">Saldo aplicado<b id="rApplied">${money(saldo)}</b></div><div class="card metric">💵 Efectivo a entregar<b id="rCash">${money(Math.max(0,cap-saldo))}</b></div><div class="card metric">Interés nuevo<b id="rInterest">${money(cap*rate/100)}</b></div><div class="card metric">Total nuevo<b id="rTotal">${money(cap+cap*rate/100)}</b></div></div></div><div class="card" id="renewalPreview"></div><div class="actionbar"><button class="btn blue" onclick="previewRenewal()">👁️ Revisar</button><button class="btn green" onclick="confirmRenewal()">✅ Confirmar y guardar</button><button class="btn" onclick="cancelRenewal()">Cancelar</button></div></div>`;document.body.appendChild(modal);$('rFreq').value=freq;['rCapital','rRate','rTerm','rFirst','rFreq'].forEach(x=>$(x)?.addEventListener('input',renderRenewal));$('rFreq')?.addEventListener('change',renderRenewal);renderRenewal()}
 function schedule(first,n,freq,total){const a=[],base=n?Math.round(total/n*100)/100:0;let d=new Date((first||today())+'T12:00:00');for(let i=1;i<=n;i++){const amount=i===n?Math.round((total-base*(n-1))*100)/100:base;a.push({n:i,date:d.toISOString().slice(0,10),amount,paid:0});if(freq==='daily')d.setDate(d.getDate()+1);else if(freq==='weekly')d.setDate(d.getDate()+7);else if(freq==='biweekly')d.setDate(d.getDate()+14);else d.setMonth(d.getMonth()+1)}return a}
 function renderRenewal(){const old=getCredit(window.__renewingCreditId);if(!old)return;const saldo=pending(old),cap=Number($('rCapital')?.value||0),rate=Number($('rRate')?.value||0),n=Number($('rTerm')?.value||0),freq=$('rFreq')?.value||'weekly',interest=cap*rate/100,total=cap+interest,cash=Math.max(0,cap-saldo),sch=schedule($('rFirst')?.value||today(),n,freq,total);$('rApplied').textContent=money(Math.min(saldo,cap));$('rCash').textContent=money(cash);$('rInterest').textContent=money(interest);$('rTotal').textContent=money(total);$('renewalPreview').innerHTML=`<h3>Vista previa final</h3><div class="info"><b>Capital nuevo:</b> ${money(cap)}</div><div class="info"><b>Saldo anterior aplicado:</b> ${money(Math.min(saldo,cap))}</div><div class="info"><b>💵 Dinero efectivo a entregar:</b> <strong>${money(cash)}</strong></div><div class="info"><b>Interés nuevo:</b> ${money(interest)} · <b>Total nuevo:</b> ${money(total)} · <b>Cuota:</b> ${money(n?total/n:0)}</div><table class="table"><tr><th>#</th><th>Fecha</th><th>Cuota</th><th>Saldo</th></tr>${sch.map((q,i)=>`<tr><td>${i+1}</td><td>${fmtDate(q.date)}</td><td>${money(q.amount)}</td><td>${money(Math.max(0,total-sch.slice(0,i+1).reduce((s,x)=>s+x.amount,0)))}</td></tr>`).join('')}</table><div class="info"><b>Resultado:</b> el crédito anterior se cierra por renovación; el nuevo crédito queda por ${money(cap)} y el cliente recibe ${money(cash)}.</div>`}
 function previewRenewal(){renderRenewal();toast('Revise el resumen antes de confirmar')}
 function confirmRenewal(){const old=getCredit(window.__renewingCreditId);if(!old)return toast('No se encontró el crédito anterior');const saldo=pending(old),cap=Number($('rCapital')?.value||0),rate=Number($('rRate')?.value||0),n=Number($('rTerm')?.value||0),freq=$('rFreq')?.value||'weekly',date=$('rDate')?.value||today(),first=$('rFirst')?.value||date;if(cap<=0||n<=0)return toast('Complete capital y plazo');if(cap<saldo)return toast('El nuevo capital no puede ser menor que el saldo pendiente');const applied=saldo,cash=cap-applied,interest=cap*rate/100,total=cap+interest,sch=schedule(first,n,freq,total);let remaining=applied;for(const q of (old.schedule||[])){const left=Math.max(0,Number(q.amount||0)-Number(q.paid||0));if(left<=0)continue;const use=Math.min(left,remaining);q.paid=Number(q.paid||0)+use;remaining-=use;if(remaining<=0)break}const newId='R'+Date.now();const payment={id:'p'+Date.now(),creditId:old.id,date,amount:applied,type:'RENOVACION_APLICADA',method:'RENOVACION',note:`Saldo aplicado al crédito nuevo #${newId}. Efectivo entregado: ${money(cash)}`};old.status='RENOVADO';old.renewedAt=date;old.renewedToId=newId;old.renewalApplied=applied;old.renewalNote=`Saldo aplicado: ${money(applied)} · Efectivo entregado: ${money(cash)}`;const cr={id:newId,clientId:old.clientId,routeId:old.routeId,date,first,capital:cap,rate,term:n,freq,total,paid:0,maturity:sch[sch.length-1]?.date||date,schedule:sch,renewedFromId:old.id,renewalApplied:applied,cashDelivered:cash,renewalType:'RENOVACION',status:'ACTIVO'};db.payments=db.payments||[];db.payments.push(payment);db.credits.push(cr);db.audit=db.audit||[];db.audit.push({id:'a'+Date.now(),date:new Date().toISOString(),action:'RENOVACION_CREDITO',detail:`Crédito #${old.id} renovado a #${newId}. Capital ${money(cap)}; saldo aplicado ${money(applied)}; efectivo entregado ${money(cash)}.`});try{persist();if(typeof enqueueSync==='function'){enqueueSync('RECAUDO',payment);enqueueSync('CREDITO_MODIFICADO',{id:old.id,renewedToId:newId,renewalApplied:applied});enqueueSync('CREDITO_CREADO',cr)}if(typeof renderAll==='function')renderAll()}catch(e){console.warn(e)}cancelRenewal();showCredit(newId);toast(`Renovación guardada · Entrega: ${money(cash)}`)}
 function cancelRenewal(){const m=$('renewalModal');if(m)m.remove()}
 wait();
})();
