// Commercial views are derived from the canonical financial records, never counters.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MiCarteraV2CommercialModel=api})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const money=n=>Math.round((Number(n)||0)*100)/100,day=v=>String(v||'').slice(0,10);
const unique=rows=>[...new Map((rows||[]).filter(x=>x&&!x.tombstone).map(x=>[String(x.id),x])).values()];
function payments(d){const reversed=new Set((d.payments||[]).filter(x=>x.recordType==='PAYMENT_REVERSAL').map(x=>String(x.reversesPaymentId)));return unique(d.payments).filter(x=>x.recordType!=='PAYMENT_REVERSAL'&&x.status!=='REVERSED'&&!reversed.has(String(x.id)))}
function records(d,type){return unique(d.commercial).filter(x=>x.recordType===type)}
function validateTerm(t){if(!['PERCENT','PER_COLLECTION','FIXED_PERIOD'].includes(t.mode))throw Error('Forma de pago inválida.');if(t.mode==='PERCENT'&&(!['TOTAL','PRINCIPAL','INTEREST','PENALTY'].includes(t.basis)||!Number.isFinite(Number(t.rate))||Number(t.rate)<0||Number(t.rate)>100))throw Error('El porcentaje debe estar entre 0 y 100 y tener una base de cálculo.');if(t.mode!=='PERCENT'&&(!(Number(t.amount)>=0)||!Number.isFinite(Number(t.amount))))throw Error('Importe fijo inválido.');if(t.mode==='FIXED_PERIOD'&&(!Number.isInteger(Number(t.periodDays))||t.periodDays<1||t.periodDays>366))throw Error('Periodo inválido (1 a 366 días).');return true}
function commissionItems(d,workerId,asOf){
  const items=[],terms=records(d,'TERM').filter(t=>String(t.workerId)===String(workerId)).sort((a,b)=>String(a.effectiveDate||'').localeCompare(String(b.effectiveDate||''))||String(a.id).localeCompare(String(b.id)));
  for(const p of payments(d).filter(p=>String(p.workerId||'')===String(workerId)&&day(p.date)<=asOf)){
    const t=terms.filter(t=>t.effectiveDate<=day(p.date)).at(-1);if(!t||t.mode==='FIXED_PERIOD')continue;
    const base=Number({TOTAL:p.amount,PRINCIPAL:p.capitalAmount,INTEREST:p.interestAmount,PENALTY:p.penaltyAmount}[t.basis]||0);
    items.push({id:t.id+':'+p.id,workerId,routeId:p.routeId||t.routeId||'',paymentId:p.id,termId:t.id,date:day(p.date),mode:t.mode,basis:t.basis,basisAmount:base,rate:Number(t.rate||0),amount:t.mode==='PER_COLLECTION'?money(t.amount):money(base*Number(t.rate)/100)});
  }
  for(let i=0;i<terms.length;i++){
    const t=terms[i];if(t.mode!=='FIXED_PERIOD'||t.effectiveDate>asOf)continue;
    const start=Date.parse(t.effectiveDate+'T00:00:00Z'),end=terms[i+1]?Math.min(Date.parse(asOf+'T00:00:00Z'),Date.parse(terms[i+1].effectiveDate+'T00:00:00Z')-86400000):Date.parse(asOf+'T00:00:00Z'),days=Math.max(0,Math.floor((end-start)/86400000)+1),periods=Math.floor(days/Number(t.periodDays));
    for(let n=0;n<periods;n++){const from=new Date(start+n*t.periodDays*86400000).toISOString().slice(0,10),to=new Date(start+((n+1)*t.periodDays-1)*86400000).toISOString().slice(0,10);items.push({id:t.id+':'+n,workerId,routeId:t.routeId||'',termId:t.id,mode:t.mode,date:to,from,to,amount:money(t.amount)})}
  }
  return items;
}
function commission(d,workerId,asOf,routeId){return money(commissionItems(d,workerId,asOf).filter(x=>!routeId||x.routeId===routeId).reduce((n,x)=>n+x.amount,0))}
function paidAllocation(x){return Array.isArray(x.commissionAllocations)&&x.commissionAllocations.length?x.commissionAllocations:[{routeId:x.routeId||'',amount:money(x.amount)}]}
function creditBalance(c){const schedule=Array.isArray(c.schedule)?c.schedule:[];if(schedule.length)return schedule.reduce((n,q)=>n+Math.max(0,Number(q.balance??(Number(q.amount||0)-Number(q.paid||0)))),0);return c.total!=null?Math.max(0,Number(c.total||0)):money(Math.max(0,money(c.capital)-money(c.principalPaid)))+Math.max(0,Number(c.interestPending??c.interestBalance??0))}
function allocateCommission(d,workerId,asOf,amount){const paid=new Map(),out=new Map();for(const x of unique(d.cashMovements).filter(x=>x.workerId===workerId&&x.type==='EGRESO'&&x.category==='COMISION_GESTOR'&&(!x.date||day(x.date)<=asOf)))for(const p of paidAllocation(x))paid.set(p.routeId,money((paid.get(p.routeId)||0)+p.amount));let remaining=money(amount);for(const item of commissionItems(d,workerId,asOf).sort((a,b)=>String(a.date||'').localeCompare(String(b.date||''))||String(a.id||'').localeCompare(String(b.id||'')))){const covered=Math.min(item.amount,paid.get(item.routeId)||0);paid.set(item.routeId,money((paid.get(item.routeId)||0)-covered));const allocated=money(Math.min(remaining,item.amount-covered));if(allocated>0){out.set(item.routeId,money((out.get(item.routeId)||0)+allocated));remaining=money(remaining-allocated)}}if(remaining!==0)throw Error('La comisión pendiente cambió. Actualiza antes de pagar.');return [...out].map(([routeId,amount])=>({routeId,amount}))}
function clientAffiliations(d,asOf){
 const groups=new Map(),allCredits=new Map((d.credits||[]).map(c=>[String(c.id),c]));
 const add=(clientId,x)=>{const group=groups.get(String(clientId));if(!group)return;const workerId=String(x.workerId||''),routeId=String(x.routeId||x.route||'');if(!group.some(v=>v.workerId===workerId&&v.routeId===routeId))group.push({workerId,routeId})};
 for(const c of unique(d.clients)){groups.set(String(c.id),[]);add(c.id,c)}
 for(const c of unique(d.credits))add(c.clientId,c);
 for(const p of payments(d))if(!asOf||day(p.date)<=asOf)add(p.clientId||allCredits.get(String(p.creditId))?.clientId,p);
 return groups;
}
function commissionPositions(d,cash,workerId,asOf,routeId,generated,paid){
 if(workerId!=null)return [{generated,paid}];
 const expenses=cash.filter(x=>x.type==='EGRESO'&&x.category==='COMISION_GESTOR'),ids=new Set([...records(d,'WORKER').map(w=>String(w.id)),...records(d,'TERM').map(t=>String(t.workerId||'')).filter(Boolean),...expenses.map(x=>String(x.workerId||''))]);
 return [...ids].map(id=>({generated:commission(d,id,asOf,routeId),paid:money(expenses.filter(x=>String(x.workerId||'')===id).reduce((n,x)=>n+(routeId?paidAllocation(x).filter(p=>p.routeId===routeId).reduce((s,p)=>s+Number(p.amount||0),0):Number(x.amount||0)),0))}));
}
function summary(d,workerId,asOf,routeId){asOf=day(asOf)||new Date().toISOString().slice(0,10);const match=x=>(workerId==null||String(x.workerId||'')===String(workerId))&&(!routeId||x.routeId===routeId);const credits=unique(d.credits).filter(match),active=credits.filter(c=>['ACTIVE','ACTIVO'].includes(c.status)&&creditBalance(c)>0),ps=payments(d).filter(p=>match(p)&&day(p.date)<=asOf),cash=unique(d.cashMovements).filter(x=>(workerId==null||String(x.workerId||'')===String(workerId))&&(!routeId||(x.category==='COMISION_GESTOR'?paidAllocation(x).some(p=>p.routeId===routeId):x.routeId===routeId))&&(!x.date||day(x.date)<=asOf)),sum=(xs,f)=>money(xs.reduce((n,x)=>n+Number(f(x)||0),0));const generated=workerId==null?0:commission(d,workerId,asOf,routeId),paid=sum(cash.filter(x=>x.type==='EGRESO'&&x.category==='COMISION_GESTOR'),x=>routeId?paidAllocation(x).filter(p=>p.routeId===routeId).reduce((n,p)=>n+p.amount,0):x.amount),interest=sum(ps,x=>x.interestAmount),penalty=sum(ps,x=>x.penaltyAmount),expenses=sum(cash.filter(x=>x.type==='EGRESO'&&!['COMISION_GESTOR','TRANSFERENCIA_GESTOR'].includes(x.category)&&!/^DESEMBOLSO|AJUSTE_RENOVACION/.test(x.concept||'')&&(!x.partnerLoanId||x.category==='INTERES_SOCIO')),x=>x.amount),positions=commissionPositions(d,cash,workerId,asOf,routeId,generated,paid),contacts=clientAffiliations(d,asOf),totalGenerated=sum(positions,p=>p.generated);return {credits:active.length,clients:unique(d.clients).filter(c=>(contacts.get(String(c.id))||[]).some(match)).length,placed:sum(active,c=>c.capital),principalPending:sum(active,c=>Math.max(0,Number(c.capital||0)-Number(c.principalPaid||0))),portfolio:sum(active,creditBalance),overdue:sum(active,c=>(c.schedule||[]).filter(q=>day(q.date)&&day(q.date)<asOf).reduce((s,q)=>s+Math.max(0,Number(q.balance??(Number(q.amount||0)-Number(q.paid||0)))),0)),collected:sum(ps,p=>p.amount),principalCollected:sum(ps,p=>p.capitalAmount),interest,penalty,delivered:sum(cash.filter(x=>x.type==='INGRESO'&&x.category==='TRANSFERENCIA_GESTOR'),x=>x.amount),cash:sum(cash.filter(x=>(workerId==null||!x.cashAccountId||x.cashAccountId===workerId)&&(!routeId||x.cashAccountId!=='leader')),x=>x.type==='INGRESO'?x.amount:x.type==='EGRESO'?-Number(x.amount):0),expenses,commissionGenerated:totalGenerated,commissionPaid:paid,commissionPending:sum(positions,p=>Math.max(0,p.generated-p.paid)),commissionOverpaid:sum(positions,p=>Math.max(0,p.paid-p.generated)),result:money(interest+penalty-expenses-totalGenerated)}}
return {money,unique,payments,records,validateTerm,commissionItems,commission,paidAllocation,allocateCommission,creditBalance,clientAffiliations,summary};
});
