// Mi Cartera PRO V2 — financial core. Pure domain logic: no DOM, no Firestore.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MiCarteraV2Financial=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const money=v=>Math.round((Number(v)||0)*100)/100;
const sid=v=>String(v??'').trim();
const STATUS=Object.freeze({ACTIVE:'ACTIVO',PAID:'PAGADO',RENEWED:'RENOVADO',VOID:'ANULADO'});
const CONCEPT=Object.freeze({CAPITAL:'CAPITAL',INTEREST:'INTERES',PENALTY:'MORA',DISCOUNT:'DESCUENTO'});
function assert(ok,msg){if(!ok)throw new Error(msg);}
function operationId(parts){return parts.map(sid).join('|');}
function normalizeCredit(c){assert(c&&sid(c.id),'CREDIT_ID_REQUIRED');const capital=money(c.capital);assert(capital>=0,'INVALID_CAPITAL');return {...c,id:sid(c.id),clientId:sid(c.clientId),capital,total:money(c.total),principalPaid:money(c.principalPaid),interestPaid:money(c.interestPaid),penaltyPaid:money(c.penaltyPaid),status:c.status||STATUS.ACTIVE,version:Number(c.version||1)};}
function principalBalance(c){c=normalizeCredit(c);return money(Math.max(0,c.capital-c.principalPaid));}
function allocatePayment(c,p){c=normalizeCredit(c);assert(p&&sid(p.id),'PAYMENT_ID_REQUIRED');const amount=money(p.amount);assert(amount>0,'INVALID_PAYMENT_AMOUNT');const concept=p.concept||CONCEPT.CAPITAL;let capitalAmount=money(p.capitalAmount),interestAmount=money(p.interestAmount),penaltyAmount=money(p.penaltyAmount);if(concept===CONCEPT.CAPITAL&&capitalAmount===0)capitalAmount=amount;if(concept===CONCEPT.INTEREST&&interestAmount===0)interestAmount=amount;if(concept===CONCEPT.PENALTY&&penaltyAmount===0)penaltyAmount=amount;assert(money(capitalAmount+interestAmount+penaltyAmount)<=amount,'PAYMENT_ALLOCATION_EXCEEDS_AMOUNT');assert(capitalAmount<=principalBalance(c),'CAPITAL_EXCEEDS_PRINCIPAL');const next={...c,principalPaid:money(c.principalPaid+capitalAmount),interestPaid:money(c.interestPaid+interestAmount),penaltyPaid:money(c.penaltyPaid+penaltyAmount),version:c.version+1};if(principalBalance(next)===0)next.status=STATUS.PAID;return {credit:next,payment:{...p,id:sid(p.id),creditId:c.id,clientId:c.clientId,amount,concept,capitalAmount,interestAmount,penaltyAmount,operationId:sid(p.operationId)||operationId(['PAY',p.id])}};}
function interestRenewal(old,input){old=normalizeCredit(old);assert(old.status===STATUS.ACTIVE,'CREDIT_NOT_ACTIVE');assert(!old.renewedTo,'CREDIT_ALREADY_RENEWED');const interest=money(input.interestAmount);assert(interest>0,'INVALID_INTEREST');const newId=sid(input.newCreditId),paymentId=sid(input.paymentId);assert(newId&&paymentId,'RENEWAL_IDS_REQUIRED');const op=sid(input.operationId)||operationId(['RENEW_INTEREST',old.id,input.date,interest]);const payment={id:paymentId,creditId:old.id,clientId:old.clientId,date:input.date,amount:interest,concept:CONCEPT.INTEREST,capitalAmount:0,interestAmount:interest,penaltyAmount:0,method:input.method||'',operationId:op};const renewedOld={...old,status:STATUS.RENEWED,interestPaid:money(old.interestPaid+interest),renewedTo:newId,renewedAt:input.date,version:old.version+1};const capital=principalBalance(old);const rate=Number(input.rate??old.rate??0);const total=money(capital*(1+rate/100));const next=normalizeCredit({id:newId,clientId:old.clientId,capital,total,principalPaid:0,interestPaid:0,penaltyPaid:0,rate,date:input.date,maturity:input.maturity,freq:input.freq||old.freq,term:input.term||old.term,status:STATUS.ACTIVE,renewedFrom:old.id,operationId:op,version:1});return {operationId:op,oldCredit:renewedOld,newCredit:next,payment};}
function refinance(old,input){old=normalizeCredit(old);assert(old.status===STATUS.ACTIVE,'CREDIT_NOT_ACTIVE');assert(!old.renewedTo,'CREDIT_ALREADY_RENEWED');const previousBalance=principalBalance(old);const newCapital=money(input.newCapital);assert(newCapital>=previousBalance,'NEW_CAPITAL_BELOW_PREVIOUS_BALANCE');const newId=sid(input.newCreditId);assert(newId,'NEW_CREDIT_ID_REQUIRED');const op=sid(input.operationId)||operationId(['REFINANCE',old.id,newId]);const rate=Number(input.rate||0);const total=money(newCapital*(1+rate/100));return {operationId:op,oldCredit:{...old,status:STATUS.RENEWED,renewedTo:newId,renewedAt:input.date,version:old.version+1},newCredit:normalizeCredit({id:newId,clientId:old.clientId,capital:newCapital,total,rate,principalPaid:0,interestPaid:0,penaltyPaid:0,date:input.date,maturity:input.maturity,freq:input.freq,term:input.term,status:STATUS.ACTIVE,renewedFrom:old.id,operationId:op,version:1}),previousBalance,cashDisbursed:money(newCapital-previousBalance)};}
function validateChain(credits){const byId=new Map(credits.map(x=>[sid(x.id),x]));const errors=[];for(const raw of credits){const c=normalizeCredit(raw);if(c.renewedTo){const n=byId.get(sid(c.renewedTo));if(!n)errors.push({code:'MISSING_RENEWED_TO',creditId:c.id});else if(sid(n.renewedFrom)!==c.id)errors.push({code:'BROKEN_RENEWAL_LINK',creditId:c.id});if(c.status!==STATUS.RENEWED)errors.push({code:'RENEWED_STATUS_MISMATCH',creditId:c.id});}if(c.renewedFrom&&!byId.has(sid(c.renewedFrom)))errors.push({code:'MISSING_RENEWED_FROM',creditId:c.id});}return errors;}
return {STATUS,CONCEPT,money,operationId,normalizeCredit,principalBalance,allocatePayment,interestRenewal,refinance,validateChain};
});