(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MiCarteraPartnerLoans=api})(globalThis,function(){
'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
function check(ok,message){if(!ok)throw Error(message)}
function money(n){check(n!==''&&Number.isFinite(Number(n)),'Importe inválido');return Math.round(Number(n)*100)/100}
function date(s){check(/^\d{4}-\d{2}-\d{2}$/.test(String(s)),'Fecha inválida');const d=new Date(s+'T12:00:00Z');check(!isNaN(d)&&d.toISOString().slice(0,10)===s,'Fecha inválida');return s}
function anniversary(start,months){date(start);const [y,m,d]=start.split('-').map(Number),last=new Date(Date.UTC(y,m-1+months+1,0)).getUTCDate();return new Date(Date.UTC(y,m-1+months,Math.min(d,last),12)).toISOString().slice(0,10)}
function create(x){const principal=money(x.principal),rate=money(x.rate);check(principal>0&&rate>0,'Capital e interés deben ser mayores a cero');check(String(x.id||'').trim()&&String(x.partner||'').trim(),'Falta socio o identificador');date(x.date);date(x.firstDue);check(x.firstDue>x.date,'El primer interés vence después de recibir el préstamo');const months=(Number(x.firstDue.slice(0,4))-Number(x.date.slice(0,4)))*12+Number(x.firstDue.slice(5,7))-Number(x.date.slice(5,7));check(months>=1&&anniversary(x.date,months)===x.firstDue,'El vencimiento debe coincidir con el día de la entrega');return {id:String(x.id),partner:String(x.partner).trim(),date:x.date,principal,rate,firstDue:x.firstDue,historical:!!x.historical,interestPayments:[],repayments:[],terms:[{from:x.firstDue,amount:money(principal*rate/100)}],closedAt:null}}
const effective=(x,asOf)=>!asOf||!x.date||x.date<=asOf;
function balance(l,asOf){if(asOf){date(asOf);if(l.date>asOf)return 0}return money(l.principal-l.repayments.filter(x=>effective(x,asOf)).reduce((s,x)=>s+x.amount,0))}
function schedule(l,until,asOf=until){
  date(until);date(asOf);
  const closedAt=l.closedAt&&l.closedAt<=asOf?l.closedAt:null,end=closedAt&&closedAt<until?closedAt:until,rows=[];
  // Each partial return appends one agreed term. A future return cannot change an earlier projection.
  const terms=l.terms.slice(0,1+l.repayments.filter(x=>effective(x,asOf)).length);
  const months=(Number(end.slice(0,4))-Number(l.date.slice(0,4)))*12+Number(end.slice(5,7))-Number(l.date.slice(5,7));check(months<=2400,'Intervalo demasiado amplio');
  for(let n=1;n<=months;n++){const d=anniversary(l.date,n);if(d<l.firstDue||d>end)continue;const term=terms.filter(x=>x.from<=d).at(-1);if(term)rows.push({date:d,amount:term.amount,paid:l.interestPayments.some(p=>p.due===d&&effective(p,asOf))})}return rows;
}
function due(l,until,asOf=until){return schedule(l,until,asOf).filter(x=>!x.paid)}
function nextDue(l,asOf){const unpaid=due(l,asOf);if(unpaid.length)return unpaid[0];if(l.closedAt&&l.closedAt<=asOf)return null;const horizon=anniversary(l.date,Math.max(1,(Number(asOf.slice(0,4))-Number(l.date.slice(0,4)))*12+Number(asOf.slice(5,7))-Number(l.date.slice(5,7)))+2);return due(l,horizon>l.firstDue?horizon:l.firstDue,asOf)[0]||null}
function payInterest(l,x){date(x.date);date(x.due);check(x.date>=x.due,'El interés todavía no vence');check(!l.interestPayments.some(p=>p.id===x.id||p.due===x.due),'Este interés ya fue pagado');const row=due(l,x.date).find(r=>r.date===x.due);check(row,'Vencimiento no pendiente');check(money(x.amount)===row.amount,'El importe no coincide con el interés de ese mes');const n=clone(l);n.interestPayments.push({id:String(x.id),date:x.date,due:x.due,amount:row.amount});return n}
function repay(l,x){date(x.date);check(x.date>=l.date,'La devolución no puede ser anterior al préstamo');check(!l.repayments.some(r=>r.id===x.id),'Devolución ya registrada');check(!l.repayments.some(r=>r.date>x.date),'Registra las devoluciones en orden de fecha');const amount=money(x.amount),pending=balance(l);check(amount>0&&amount<=pending,'La devolución excede el capital pendiente');const n=clone(l);if(amount<pending){check(x.nextMonthlyInterest!==undefined,'Confirma el próximo interés mensual acordado');const future=money(x.nextMonthlyInterest);check(future>0,'El próximo interés debe ser mayor a cero');const months=(Number(x.date.slice(0,4))-Number(l.date.slice(0,4)))*12+Number(x.date.slice(5,7))-Number(l.date.slice(5,7));let from=anniversary(l.date,Math.max(1,months));if(from<=x.date)from=anniversary(l.date,Math.max(1,months)+1);check(!l.interestPayments.some(p=>p.due>=from),'Hay intereses posteriores pagados; revisa las fechas');n.terms.push({from,amount:future});}else{check(!l.interestPayments.some(p=>p.due>x.date),'Hay intereses posteriores pagados; revisa las fechas');n.closedAt=x.date;}n.repayments.push({id:String(x.id),date:x.date,amount});return n}
function entry(l){return {id:l.id,date:l.date,type:'INGRESO',amount:l.historical?0:l.principal,category:'PRESTAMO_SOCIO',concept:'Préstamo de '+l.partner,ref:l.id,version:1,partnerLoan:clone(l)}}
function summary(movements,credits,asOf){date(asOf);const rows=movements.filter(x=>!x.tombstone&&effective(x,asOf)),loans=rows.filter(x=>x.partnerLoan&&x.partnerLoan.date<=asOf).map(x=>x.partnerLoan),cash=money(rows.reduce((n,m)=>n+(m.type==='INGRESO'?Number(m.amount||0):m.type==='EGRESO'?-Number(m.amount||0):0),0)),portfolioPrincipal=money(credits.filter(c=>!c.tombstone&&effective(c,asOf)&&['ACTIVO','ACTIVE'].includes(c.status)).reduce((n,c)=>n+Math.max(0,Number(c.capital||0)-Number(c.principalPaid||0)),0)),partnerPrincipal=money(loans.reduce((n,l)=>n+balance(l,asOf),0)),partnerInterestDue=money(loans.reduce((n,l)=>n+due(l,asOf).reduce((a,b)=>a+b.amount,0),0)),partnerInterestPaid=money(rows.filter(m=>m.type==='EGRESO'&&m.category==='INTERES_SOCIO').reduce((n,m)=>n+Number(m.amount||0),0));return {cash,portfolioPrincipal,partnerPrincipal,partnerInterestDue,partnerInterestPaid,netCapital:money(cash+portfolioPrincipal-partnerPrincipal-partnerInterestDue)}}
return {summary,create,balance,due,schedule,nextDue,payInterest,repay,entry,anniversary,money,date};
});
