// Mi Cartera PRO V2 — deterministic installment schedules.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.MiCarteraV2Schedule=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){'use strict';
const money=n=>Math.round((Number(n)||0)*100)/100;const DAY=86400000;
function iso(d){return new Date(d).toISOString().slice(0,10)}
function parseDate(s){const d=new Date(String(s)+'T12:00:00Z');if(Number.isNaN(d.getTime()))throw new Error('INVALID_START_DATE');return d}
function addMonths(date,n){const d=new Date(date);const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d}
function nextDate(start,freq,index){if(freq==='daily')return new Date(start.getTime()+DAY*index);if(freq==='weekly')return new Date(start.getTime()+DAY*7*index);if(freq==='biweekly')return new Date(start.getTime()+DAY*14*index);if(freq==='monthly')return addMonths(start,index);throw new Error('INVALID_FREQUENCY')}
function validRestDay(restDay){if(restDay==null||restDay==='')return null;const r=Number(restDay);if(!Number.isInteger(r)||r<0||r>6)throw new Error('INVALID_REST_DAY');return r}
function nextBusinessDue(candidate,restDay,previous){const r=validRestDay(restDay);let d=new Date(candidate);if(r!==null&&d.getUTCDay()===r)d.setUTCDate(d.getUTCDate()+1);if(previous){const p=parseDate(previous);while(d.getTime()<=p.getTime()){d.setUTCDate(d.getUTCDate()+1);if(r!==null&&d.getUTCDay()===r)d.setUTCDate(d.getUTCDate()+1);}}return d}
function generate(input){const total=money(input?.total),term=Number(input?.term),freq=String(input?.freq||'').toLowerCase();if(!(total>0))throw new Error('TOTAL_REQUIRED');if(!Number.isInteger(term)||term<1)throw new Error('TERM_REQUIRED');const start=parseDate(input.firstPaymentDate);const base=Math.floor((total*100)/term)/100;let allocated=0,previous=null;const rows=[];for(let i=1;i<=term;i++){const amount=i===term?money(total-allocated):base;allocated=money(allocated+amount);const due=nextBusinessDue(nextDate(start,freq,i-1),input.restDay,previous);previous=iso(due);rows.push({number:i,date:previous,amount,paid:0,balance:amount,status:'PENDIENTE'});}if(money(rows.reduce((s,x)=>s+x.amount,0))!==total)throw new Error('SCHEDULE_TOTAL_MISMATCH');if(new Set(rows.map(x=>x.date)).size!==rows.length)throw new Error('SCHEDULE_DATE_COLLISION');return rows}
return {generate};});