const {test}=require('node:test'),a=require('node:assert/strict'),crypto=require('node:crypto'),{boot,KEY}=require('./dom-harness.cjs');
async function fixture(){
 const h=await boot(),w=h.w,uid='test-admin',key='mi-cartera-v2-cloud-operations:'+uid;
 Object.defineProperty(w,'crypto',{value:crypto.webcrypto,configurable:true});
 Object.defineProperty(w.navigator,'locks',{value:{request:async(_n,_o,fn)=>fn({})},configurable:true});
 for(const f of ['core/transaction-store.js','core/sync-errors.js','core/offline-operation-queue.js'])h.load(f);
 const rows=['ERROR','PENDIENTE'].map((status,i)=>({id:'fictional-admin-close-'+i,status,attempts:i?0:8,lastError:i?null:'NETWORK_TIMEOUT',nextAttemptAt:0,createdAt:'2026-10-03T15:00:00Z',operation:{id:'fictional-admin-close-'+i,operationId:'fictional-admin-close-'+i,actorId:uid,type:'PAYMENT',createdAt:'2026-10-03T15:00:00Z',writes:[{kind:'create',path:'payments/fictional-pay-'+i,data:{id:'fictional-pay-'+i,amount:10,clientId:'c1',creditId:'credit-'+i,date:'2026-10-03',version:1},expectedVersion:0}]}}));
 const raw=JSON.stringify(rows,null,2);w.localStorage.setItem(key,raw);w.localStorage.setItem('mi-cartera-v2-local-owner',uid);
 const d=h.get();d.session.role='admin';d.session.routeIds=[];d.session.workerId='';h.set(d);
 w.MI_CARTERA_ADMIN_CLOSURE_AUTHORIZATION={ownerHash:crypto.createHash('sha256').update(uid).digest('hex'),reference:'QA_EXPLICIT_ADMIN_CONFIRMATION',reason:'CLOUD_HTTP_429',hashes:rows.map(x=>crypto.createHash('sha256').update(uid+'|'+x.id+'|'+w.MiCarteraV2Store.fingerprint(x.operation)).digest('hex'))};
 h.load('app/pending-review-v2.js');
 const closeAdmin=options=>w.MiCarteraV2PendingReview.confirmAdministrative({confirmedByAdministrator:true,expectedRaw:raw,...options});
 return {...h,key,rows,raw,closeAdmin,queue:()=>w.MiCarteraV2OfflineQueue.createQueue(w.localStorage,key)};
}
test('explicit administrative closure requires no Cloud, preserves original journal and business bytes, and records honest local audit',async()=>{const h=await fixture();try{
 const before=h.w.localStorage.getItem(KEY);let cloudCalls=0;h.w.firestoreV2={getDocFromServer:()=>{cloudCalls++;throw Error('HTTP429')}};
 const r=await h.closeAdmin();a.equal(r.closed,2);a.equal(r.pending,0);a.equal(cloudCalls,0);a.equal(h.w.localStorage.getItem(KEY),before);a.equal(h.w.localStorage.getItem(r.backupKey),h.raw);
 const rows=JSON.parse(h.w.localStorage.getItem(h.key));rows.forEach((x,i)=>{a.equal(x.status,'CERRADO_ADMIN');a.deepEqual(x.operation,h.rows[i].operation);a.equal(x.attempts,h.rows[i].attempts);a.equal(x.lastError,h.rows[i].lastError);a.equal(x.administrativeClosure.actorId,'test-admin');a.equal(x.administrativeClosure.reason,'CLOUD_HTTP_429');a.equal(x.administrativeClosure.serverApplied,'NOT_VERIFIED');a.equal(x.administrativeClosure.noReplay,true);a.equal(x.administrativeClosure.previousStatus,h.rows[i].status)});a.equal(h.w.MiCarteraV2PendingReview.pending().length,0);a.equal(h.commits.length,0);
}finally{h.close()}});
test('a fresh collection pending after quota or uncertain delivery remains resumable after runtime reload while closed originals never send',async()=>{for(const prepared of [false,true]){const h=await fixture();try{
 await h.closeAdmin();const q=h.queue(),op={id:'reload-new-fictitious',operationId:'reload-new-fictitious',actorId:'test-admin',type:'PAYMENT',requiresLeaderCashRevision:true,writes:[{kind:'create',path:'payments/reload-new-fictitious',data:{id:'reload-new-fictitious',amount:90,version:1},expectedVersion:0}]};await q.enqueue(op);let preparations=0,sent=[];
 const prepare=async original=>{preparations++;const output={...original,writes:original.writes.concat({kind:'create',path:'routes/leader-cash-revision',expectedVersion:0,data:{id:'leader-cash-revision',version:1}})};delete output.requiresLeaderCashRevision;return output};if(prepared)await q.prepareForExecution(op.id,prepare);
 const source=h.w.localStorage.getItem(h.key);h.w.MiCarteraV2Store.createStore=()=>({execute:async current=>{sent.push(structuredClone(current));return {status:'APPLIED'}}});h.w.MiCarteraV2FirestoreAdapter={createFirestoreAtomicAdapter:()=>({})};h.w.MiCarteraV2PilotConfig={evaluate:()=>({ready:true})};h.w.MiCarteraV2CommercialActions={prepareQueuedOperation:prepare};for(const f of ['cloud/operational-sync.js','app/operation-sync-bridge.js','cloud/runtime-cloud.js'])h.load(f);const r=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});a.equal(h.w.MiCarteraV2SyncBridge.status().reviewRequired,false);await r.flush();a.equal(sent.length,1);a.equal(sent[0].id,op.id);a.equal(preparations,1);if(prepared)a.deepEqual(sent[0],JSON.parse(source).find(x=>x.id===op.id).operation);a.equal(h.w.MiCarteraV2SyncBridge.status().pending,0);
}finally{h.close()}}});
test('quota-only administrator lease fallback is scoped, expires and never renews a failed Cloud membership read',async()=>{for(const mode of ['valid','wrong-owner','expired','future','invalid-time','wrong-role','inactive','denied','expired-after-ready']){const h=await fixture();let originalNow;try{
 const key='v2-member:v2-mi-cartera-pilot:test-admin',at=Date.now()-1000,lease={at,member:{active:true,role:'admin',routeIds:[]}};if(mode==='expired')lease.at=Date.now()-86400001;if(mode==='future')lease.at=Date.now()+1000;if(mode==='invalid-time')lease.at='invalid';if(mode==='wrong-role')lease.member.role='gestor';if(mode==='inactive')lease.member.active=false;if(mode==='wrong-owner')h.w.MI_CARTERA_ADMIN_CLOSURE_AUTHORIZATION.ownerHash='another-owner';h.w.localStorage.setItem(key,JSON.stringify(lease));const raw=h.w.localStorage.getItem(key);
 h.w.firebaseAuthV2={auth:{currentUser:{uid:'test-admin'}},onAuthStateChanged:()=>()=>{}};h.w.firestoreV2={db:{},doc:()=>({}),getDoc:async()=>{throw Object.assign(Error(mode==='denied'?'permission-denied':'HTTP 429'),{code:mode==='denied'?'permission-denied':429})}};h.w.MiCarteraV2CloudRuntime={configure(){}};h.load('app/auth-cloud-gate.js');await h.w.MiCarteraV2AuthCloudGate.refreshMembership();const valid=['valid','expired-after-ready'].includes(mode);a.equal(h.w.MiCarteraV2AuthCloudGate.state().ready,valid,mode);if(!valid&&mode!=='denied')a.ok(h.w.MiCarteraV2AuthCloudGate.state().nextMembershipAttemptAt>Date.now(),'pure HTTP429 needs a bounded membership retry');a.equal(h.w.localStorage.getItem(key),raw,'failed server read must not extend the verified lease');if(mode==='expired-after-ready'){originalNow=h.w.Date.now;h.w.Date.now=()=>at+86400001;a.equal(h.w.MiCarteraV2AuthCloudGate.state().ready,false);a.throws(()=>h.w.MiCarteraV2AuthCloudGate.requireReady(),/EXPIRED/)}a.equal(h.commits.length,0);
}finally{if(originalNow)h.w.Date.now=originalNow;h.close()}}});
test('closed original IDs cannot execute after reopening, reconnecting, repeated flush or restoring a stale queue copy',async()=>{const h=await fixture();try{
 await h.closeAdmin();let sent=[];let q=h.queue();a.equal((await q.flush(async op=>{sent.push(op.id);return {status:'APPLIED'}})).applied,0);
 h.w.localStorage.setItem(h.key,h.raw);q=h.queue();a.equal(q.inspect().filter(x=>!h.w.MiCarteraV2OfflineQueue.isTerminal(x)).length,0);await q.flush(async op=>{sent.push(op.id);return {status:'APPLIED'}});
 await a.rejects(()=>q.enqueue(h.rows[0].operation),/ADMINISTRATIVE_OPERATION_CLOSED/);
 await q.enqueue({id:'fictional-new',operationId:'fictional-new',actorId:'test-admin',type:'PAYMENT',writes:[]});await q.flush(async op=>{sent.push(op.id);return {status:'APPLIED'}});await q.flush(async op=>{sent.push(op.id);return {status:'APPLIED'}});a.deepEqual(sent,['fictional-new']);a.equal(h.commits.length,0);
}finally{h.close()}});
test('wrong role, unapproved payload, changed source, incomplete selection or absent consent cannot close a journal',async()=>{for(const mode of ['role','scope','payload','source','consent','partial']){const h=await fixture();try{
 let options={};if(mode==='role')h.w.MiCarteraV2AuthCloudGate.state=()=>({ready:true,uid:'test-admin',role:'gestor'});
 if(mode==='scope')h.w.MI_CARTERA_ADMIN_CLOSURE_AUTHORIZATION.hashes=['unknown'];
 if(mode==='payload'){const rows=structuredClone(h.rows);rows[0].operation.writes[0].data.amount=11;h.w.localStorage.setItem(h.key,JSON.stringify(rows));options.expectedRaw=JSON.stringify(rows)}
 if(mode==='source')h.w.localStorage.setItem(h.key,h.raw+' ');if(mode==='consent')options.confirmedByAdministrator=false;
 if(mode==='partial'){h.w.localStorage.setItem(h.key,JSON.stringify([h.rows[0]]));options.expectedRaw=JSON.stringify([h.rows[0]])}
 const source=h.w.localStorage.getItem(h.key),business=h.w.localStorage.getItem(KEY);await a.rejects(()=>h.closeAdmin(options));a.equal(h.w.localStorage.getItem(h.key),source);a.equal(h.w.localStorage.getItem(KEY),business);a.equal(h.queue().inspect().filter(x=>x.status==='CERRADO_ADMIN').length,0);
}finally{h.close()}}});
test('backup or ledger write failure cannot discard or acknowledge either original',async()=>{for(const failure of ['backup','ledger']){const h=await fixture();try{
 const storage=h.w.localStorage;Object.defineProperty(h.w,'localStorage',{value:{getItem:storage.getItem.bind(storage),key:storage.key.bind(storage),get length(){return storage.length},setItem:(k,v)=>{if(failure==='backup'?k.startsWith('mi-cartera-v2-journal-review-backup:'):k.startsWith('mi-cartera-v2-journal-admin-closures:'))throw Error('STORAGE_FULL');storage.setItem(k,v)}},configurable:true});await a.rejects(()=>h.closeAdmin(),/STORAGE_FULL/);a.equal(storage.getItem(h.key),h.raw);a.equal(h.queue().inspect().filter(x=>x.status==='CERRADO_ADMIN').length,0);
}finally{h.close()}}});
test('a completed exclusion ledger remains authoritative even if the final queue metadata write fails',async()=>{const h=await fixture();try{
 const storage=h.w.localStorage;Object.defineProperty(h.w,'localStorage',{value:{getItem:storage.getItem.bind(storage),key:storage.key.bind(storage),get length(){return storage.length},setItem:(k,v)=>{if(k===h.key)throw Error('STORAGE_FULL');storage.setItem(k,v)}},configurable:true});const r=await h.closeAdmin();a.equal(r.closed,2);a.equal(r.pending,0);a.equal(storage.getItem(h.key),h.raw);a.equal(h.queue().inspect().filter(x=>x.status==='CERRADO_ADMIN').length,2);let sent=0;await h.queue().flush(async()=>{sent++;return {status:'APPLIED'}});a.equal(sent,0);a.equal(h.w.MiCarteraV2PendingReview.pending().length,0);
}finally{h.close()}});
test('administrative closure prevents Cloud rehydration from replacing local financial records',async()=>{const h=await fixture();try{
 await h.closeAdmin();h.load('app/cloud-rehydration-v2.js');let reads=0;h.w.firestoreV2={db:{},collection:()=>({}),getDocs:async()=>{reads++;return {forEach(){}}}};const before=h.w.localStorage.getItem(KEY);const r=await h.w.MiCarteraV2CloudRehydration.rehydrate();a.equal(r.status,'SKIPPED_ADMINISTRATIVE_CLOSURES');a.equal(h.w.localStorage.getItem(KEY),before);a.equal(reads,0);
}finally{h.close()}});
test('mobile diary opening is read-only and administrative confirmation displays closed audit with zero pending',async()=>{const h=await fixture();try{
 h.w.HTMLAnchorElement.prototype.click=()=>{};const before=h.w.localStorage.getItem(h.key);h.w.MiCarteraV2PendingReview.open();await new Promise(r=>setTimeout(r,20));a.equal(h.w.localStorage.getItem(h.key),before);const panel=h.w.document.getElementById('v2PendingReview'),b=panel.querySelector('[data-admin-confirm]');a.equal(b.hidden,false);panel.querySelector('[data-admin-consent]').checked=true;await b.onclick();a.match(panel.querySelector('[data-confirm-status]').textContent,/2.*cerradas.*0 pendientes/i);a.match(panel.querySelector('[data-rows]').textContent,/administrador|administrativ/i);a.match(panel.querySelector('[data-rows]').textContent,/Cloud.*sin|sin.*Cloud|no.*verific/i);a.equal(h.w.MiCarteraV2PendingReview.snapshot().administrativeClosures!=null,true);a.equal(h.commits.length,0);
}finally{h.close()}});
test('a new fictional collection is durable during quota exhaustion and only that new collection can synchronize with a freshly persisted cash guard',async()=>{const h=await fixture();try{
 await h.closeAdmin();for(const f of ['core/commercial-model.js','app/commercial-actions-v2.js','cloud/operational-sync.js','app/operation-sync-bridge.js'])h.load(f);
 let quota=true,sent=[];h.w.firestoreV2={db:{},doc:(_db,...p)=>p,getDoc:async()=>{if(quota)throw Object.assign(Error('Quota exceeded'),{code:'resource-exhausted'});return {exists:()=>true,data:()=>({id:'leader-cash-revision',recordType:'LEADER_CASH_REVISION',version:12})}}};
 const q=h.queue(),s=h.w.MiCarteraV2OperationalSync.createOperationalSync({actorId:'test-admin',queue:q,prepareQueuedOperation:op=>h.w.MiCarteraV2CommercialActions.prepareQueuedOperation(op),store:{execute:async op=>{sent.push(structuredClone(op));const saved=JSON.parse(h.w.localStorage.getItem(h.key)).find(x=>x.id===op.id);a.deepEqual(saved.operation,structuredClone(op));return {status:'APPLIED'}}}});h.w.MiCarteraV2SyncBridge.configure(s);
 const input={operationId:'fictional-fresh-90',type:'PAYMENT',entities:[{collection:'payments',kind:'create',data:{id:'fictional-fresh-pay',amount:90,version:1}},{collection:'entries',kind:'create',data:{id:'fictional-fresh-cash',amount:90,type:'INGRESO',version:1}}]};
 const r=await h.w.MiCarteraV2OperationCommitGate.submit({bridge:h.w.MiCarteraV2SyncBridge,versionGuard:h.w.MiCarteraV2VersionGuard,authGate:h.w.MiCarteraV2AuthCloudGate,operation:input});a.equal(r.status,'QUEUED');a.equal(r.durable,true);a.equal(sent.length,0);a.equal(h.w.MiCarteraV2SyncBridge.status().pending,1);
 await s.flush();a.equal(sent.length,0);quota=false;await new Promise(r=>setTimeout(r,2100));await s.flush();a.equal(sent.length,1);a.equal(sent[0].id,'fictional-fresh-90');const guard=sent[0].writes.find(x=>x.path==='routes/leader-cash-revision');a.equal(guard.expectedVersion,12);a.equal(guard.data.version,13);a.equal(h.w.MiCarteraV2SyncBridge.status().pending,0);a.equal(q.inspect().filter(x=>x.status==='CERRADO_ADMIN').length,2);
}finally{h.close()}});
test('quota fallback never accepts an expense, credit renewal or capital/commission disbursement',async()=>{const h=await fixture();try{
 await h.closeAdmin();for(const f of ['core/commercial-model.js','app/commercial-actions-v2.js'])h.load(f);h.w.firestoreV2={db:{},doc:()=>({}),getDoc:async()=>{throw Object.assign(Error('Quota exceeded'),{code:'resource-exhausted'})}};
 for(const type of ['CREDIT_RENEW','WORKER_FUNDED','WORKER_COMMISSION_PAID','PAYMENT']){const op={operationId:'rejected-'+type,type,entities:[{collection:'expenses',kind:'create',data:{id:'expense-'+type,amount:90,type:'EGRESO',version:1}}]};await a.rejects(()=>h.w.MiCarteraV2CommercialActions.prepareOperation(op),/Quota exceeded/);a.equal(op.requiresLeaderCashRevision,undefined)}a.equal(h.commits.length,0);
}finally{h.close()}});
test('a Cloud read started before closure cannot overwrite the local portfolio after closure',async()=>{const h=await fixture();try{
 let releases=[];h.w.localStorage.setItem(h.key,'[]');h.w.firestoreV2={db:{},collection:()=>({}),getDocs:()=>new Promise(r=>releases.push(()=>r({forEach(){}})))};h.load('app/cloud-rehydration-v2.js');const before=h.w.localStorage.getItem(KEY),hydrating=h.w.MiCarteraV2CloudRehydration.rehydrate();await new Promise(r=>setTimeout(r,5));a.ok(releases.length>0);h.w.localStorage.setItem(h.key,h.raw);await h.closeAdmin();releases.forEach(r=>r());const result=await hydrating;a.equal(result.status,'SKIPPED_ADMINISTRATIVE_CLOSURES');a.equal(h.w.localStorage.getItem(KEY),before);a.equal(h.commits.length,0);
}finally{h.close()}});
test('PWA update preserves the exact closed journal, exclusion ledger, complete source backup and financial portfolio',async()=>{const h=await fixture();try{
 const fs=require('node:fs'),vm=require('node:vm'),result=await h.closeAdmin(),keys=[h.key,result.ledgerKey,result.backupKey,KEY],original=new Map(keys.map(k=>[k,h.w.localStorage.getItem(k)])),handlers={},cache=new Map();
 const context={Request:class{constructor(url){this.url=url}},URL,console,setTimeout,clearTimeout,caches:{open:async name=>{cache.set(name,[]);return {addAll:async urls=>cache.get(name).push(...urls)}},keys:async()=>[...cache.keys()],delete:async key=>cache.delete(key)},self:{addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}},location:{origin:'https://local.test'}},localStorage:{getItem:k=>h.w.localStorage.getItem(k),setItem(){throw Error('SW_STORAGE_WRITE_FORBIDDEN')},removeItem(){throw Error('SW_STORAGE_DELETE_FORBIDDEN')},clear(){throw Error('SW_STORAGE_CLEAR_FORBIDDEN')}}};
 vm.runInNewContext(fs.readFileSync('v2/app/service-worker.js','utf8'),context);for(const event of ['install','activate']){let done;handlers[event]({waitUntil:p=>done=p});await done;for(const key of keys)a.equal(h.w.localStorage.getItem(key),original.get(key))}a.equal(h.w.MiCarteraV2PendingReview.pending().length,0);let sent=0;await h.queue().flush(async()=>{sent++;return {status:'APPLIED'}});a.equal(sent,0);for(const key of keys)a.equal(h.w.localStorage.getItem(key),original.get(key));
}finally{h.close()}});
test('concurrent deferred flushes reuse one persisted fingerprint after uncertain delivery and never execute either closed receipt',async()=>{const h=await fixture();try{
 const locks=new Map();Object.defineProperty(h.w.navigator,'locks',{value:{request:(key,_o,fn)=>{const prior=locks.get(key)||Promise.resolve(),next=prior.catch(()=>{}).then(()=>fn({}));locks.set(key,next);return next}},configurable:true});await h.closeAdmin();h.load('cloud/operational-sync.js');
 const db=new Map([['routes/leader-cash-revision',{id:'leader-cash-revision',version:12}]]);let atomic=Promise.resolve();const adapter={runAtomic:fn=>{const run=atomic.then(async()=>{const copy=new Map(db),r=await fn({get:async p=>copy.get(p),set:async(p,v)=>copy.set(p,structuredClone(v))});db.clear();for(const [k,v] of copy)db.set(k,v);return r});atomic=run.catch(()=>{});return run}},store=h.w.MiCarteraV2Store.createStore(adapter);
 const first=h.queue(),second=h.queue(),op={id:'concurrent-fictional-new',operationId:'concurrent-fictional-new',actorId:'test-admin',type:'PAYMENT',requiresLeaderCashRevision:true,writes:[{kind:'create',path:'payments/concurrent-fictional-new',data:{id:'concurrent-fictional-new',amount:90,version:1},expectedVersion:0}]};await first.enqueue(op);let prepared=0,sent=[];
 const config=queue=>({actorId:'test-admin',queue,prepareQueuedOperation:async original=>{prepared++;await new Promise(r=>setTimeout(r,5));const output={...original,writes:original.writes.concat({kind:'set',path:'routes/leader-cash-revision',expectedVersion:12,data:{id:'leader-cash-revision',version:13}})};delete output.requiresLeaderCashRevision;return output},store:{execute:async original=>{sent.push(structuredClone(original));const r=await store.execute(original);if(sent.length===1)throw Object.assign(Error('NETWORK_TIMEOUT'),{code:'deadline-exceeded'});return r}}});
 const one=h.w.MiCarteraV2OperationalSync.createOperationalSync(config(first)),two=h.w.MiCarteraV2OperationalSync.createOperationalSync(config(second));await Promise.all([one.flush(),two.flush()]);a.equal(prepared,1);a.equal(sent.length,2);a.deepEqual(sent[0],sent[1]);a.equal(db.get('routes/leader-cash-revision').version,13);a.equal(db.get('payments/concurrent-fictional-new').amount,90);a.equal(first.inspect().filter(x=>!h.w.MiCarteraV2OfflineQueue.isTerminal(x)).length,0);for(const old of h.rows)a.equal(db.has(old.operation.writes[0].path),false);
}finally{h.close()}});
test('refresh verifies the app version without falsely claiming a Cloud financial refresh after administrative closure',async()=>{const h=await fixture();try{
 await h.closeAdmin();h.load('app/cloud-rehydration-v2.js');h.load('app/refresh-controller-v2.js');h.w.MiCarteraV2Refresh.install();await h.w.MiCarteraV2Refresh.run();const button=h.w.document.getElementById('manualRefreshButton');a.match(button.title,/Cloud.*sin verificar|sin verificar.*Cloud/i);a.doesNotMatch(button.title,/Datos y versión verificados/i);a.equal(h.commits.length,0);
}finally{h.close()}});
test('a deferred cash revision timeout stays retryable and missing Web Locks cannot prepare or send a new operation',async()=>{const h=await fixture();try{
 await h.closeAdmin();for(const f of ['core/commercial-model.js','app/commercial-actions-v2.js'])h.load(f);h.w.firestoreV2={db:{},doc:()=>({}),getDoc:()=>new Promise(()=>{})};const timer=h.w.setTimeout;h.w.setTimeout=(fn,ms)=>timer(fn,ms===5000?1:ms);await a.rejects(()=>h.w.MiCarteraV2CommercialActions.readLeaderRevision(),e=>e.code==='deadline-exceeded');
 const q=h.queue();await q.enqueue({id:'lock-test-new',operationId:'lock-test-new',actorId:'test-admin',type:'PAYMENT',requiresLeaderCashRevision:true,writes:[{kind:'create',path:'payments/lock-test-new',data:{id:'lock-test-new',amount:90},expectedVersion:0}]});const source=h.w.localStorage.getItem(h.key);Object.defineProperty(h.w.navigator,'locks',{value:undefined});let prepared=0;await a.rejects(()=>q.prepareForExecution('lock-test-new',()=>{prepared++;return {}}),/LOCK_REQUIRED/);a.equal(prepared,0);a.equal(h.w.localStorage.getItem(h.key),source);
}finally{h.close()}});
