const {test}=require('node:test'),a=require('node:assert/strict'),C=require('../core/commercial-model.js'),{boot}=require('./dom-harness.cjs');
const base=()=>({clients:[{id:'qa-c',workerId:'qa-w',routeId:'qa-r'}],credits:[],payments:[],cashMovements:[],commercial:[]});
test('legacy principal-only consultation uses the approved cent normalization before deciding whether a credit remains active',()=>{
 for(const [principalPaid,expectedBalance,expectedCredits] of [[100,0,0],[30.006,76.99,1]]){const d=base();d.credits=[{id:'qa-rounding',clientId:'qa-c',workerId:'qa-w',routeId:'qa-r',capital:100.004,principalPaid,interestPending:principalPaid===100?0:7,status:'ACTIVO'}];const before=JSON.stringify(d),s=C.summary(d,'qa-w','2026-10-03');a.equal(s.portfolio,expectedBalance);a.equal(s.credits,expectedCredits);a.equal(JSON.stringify(d),before);}
});
test('route and worker portfolio retain the supported balance of an active legacy credit without a schedule',()=>{
 const d=base();d.credits=[{id:'qa-legacy',clientId:'qa-c',workerId:'qa-w',routeId:'qa-r',capital:100,total:110,status:'ACTIVO',date:'2026-10-01'}];const before=JSON.stringify(d);
 for(const [worker,route] of [['qa-w',undefined],[null,'qa-r'],[null,undefined]]){const s=C.summary(d,worker,'2026-10-03',route);a.equal(s.portfolio,110);a.equal(s.credits,1);a.equal(s.placed,100);a.equal(s.overdue,0,'No dates are invented for a missing schedule');}
 a.equal(JSON.stringify(d),before);
});
test('zero-balance active rows are finalized in commercial consultation without rewriting history or commission inputs',()=>{
 const d=base();d.credits=[{id:'qa-paid',clientId:'qa-c',workerId:'qa-w',routeId:'qa-r',capital:100,total:110,status:'ACTIVO',schedule:[{amount:110,paid:110,balance:0,date:'2026-09-01'}]},{id:'qa-partial',clientId:'qa-c',workerId:'qa-w',routeId:'qa-r',capital:200,total:220,principalPaid:100,status:'ACTIVO',schedule:[{amount:220,balance:110,date:'2026-09-01'}]}];d.payments=[{id:'qa-history',workerId:'qa-w',routeId:'qa-r',creditId:'qa-paid',date:'2026-10-01',amount:110,capitalAmount:100,interestAmount:10}];d.commercial=[{id:'qa-term',recordType:'TERM',workerId:'qa-w',routeId:'qa-r',effectiveDate:'2026-10-01',mode:'PERCENT',basis:'INTEREST',rate:20}];const before=JSON.stringify(d),s=C.summary(d,'qa-w','2026-10-03');
 a.equal(s.credits,1);a.equal(s.placed,200);a.equal(s.principalPending,100);a.equal(s.portfolio,110);a.equal(s.overdue,110);a.equal(s.collected,110);a.equal(s.commissionGenerated,2);a.equal(JSON.stringify(d),before);
});
test('mobile Rutas shows the legacy portfolio and its consultation excludes a fully paid active row without saving anything',async()=>{
 const h=await boot();try{const d=h.get();d.commercial=[{id:'qa-r',recordType:'ROUTE',name:'Ruta ficticia',active:true},{id:'qa-w',recordType:'WORKER',name:'Gestora ficticia',routeId:'qa-r',active:true}];d.credits=[{id:'qa-legacy',clientId:'c1',workerId:'qa-w',routeId:'qa-r',capital:100,total:110,status:'ACTIVO',date:'2026-10-01'},{id:'qa-paid',clientId:'c1',workerId:'qa-w',routeId:'qa-r',capital:200,total:220,status:'ACTIVO',schedule:[{amount:220,balance:0}]}];h.set(d);const original=h.w.localStorage.getItem('mi-cartera-v2-validation-state');for(const f of ['core/commercial-model.js','app/commercial-actions-v2.js','app/operational-cards-v2.js','app/inspection-v2.js','app/commercial-ui-v2.js'])h.load(f);const ui=h.w.MiCarteraV2CommercialUI;ui.install();ui.detail('qa-w');const b=[...h.w.document.querySelectorAll('#v2CommercialDetails .v2-com-metric')].find(x=>x.textContent.startsWith('Cartera pendiente'));a.ok(b);a.match(b.textContent,/110\.00/);b.click();a.equal(h.w.document.querySelectorAll('#v2InspectionRows .v2-inspect-row').length,1);a.equal(h.w.localStorage.getItem('mi-cartera-v2-validation-state'),original);a.equal(h.commits.length,0);}finally{h.close()}
});
