const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const file=path.resolve(process.env.SOURCE||'v2','core/customer-history.js');
const C=fs.existsSync(file)?require(file):null;
function summary(d,id='c1',date='2026-09-10'){a.equal(typeof C?.summary,'function','El modelo de historial de consulta debe estar disponible');return C.summary(d,id,date)}
function credit(id,rows,status='ACTIVO'){return {id,clientId:'c1',capital:rows.length*90,total:rows.length*100,principalPaid:0,status,schedule:rows.map((q,i)=>({number:i+1,date:q.date,amount:100,paid:q.paid?100:0,balance:q.paid?0:100,status:q.paid?'PAGADA':'PENDIENTE'}))}}
function payment(id,creditId,number,date,amount=100){return {id,creditId,clientId:'c1',date,amount,concept:'CUOTA',capitalAmount:amount*.9,interestAmount:amount*.1,penaltyAmount:0,allocations:[{installmentNumber:number,amount}],version:1}}
test('el perfil sin historial es gris y no inventa puntualidad ni tendencia',()=>{const r=summary({credits:[],payments:[]});a.equal(r.grantedCredits,0);a.equal(r.trafficLight.color,'gray');a.equal(r.punctualityRate,null);a.equal(r.averageDelayDays,null);a.equal(r.trend,null)});
test('deriva cuotas y cumplimiento de allocations reales y excluye pagos revertidos sin mutar datos',()=>{const d={credits:[credit('cr1',[{date:'2026-09-01',paid:true},{date:'2026-09-03',paid:true},{date:'2026-09-05',paid:false}])],payments:[payment('p1','cr1',1,'2026-09-01'),payment('p2','cr1',2,'2026-09-05'),payment('p3','cr1',3,'2026-09-06'),{id:'undo',recordType:'PAYMENT_REVERSAL',reversesPaymentId:'p3',tombstone:true}]},before=JSON.stringify(d),r=summary(d);a.equal(r.grantedCredits,1);a.equal(r.activeCredits,1);a.equal(r.paidInstallments,2);a.equal(r.onTimeInstallments,1);a.equal(r.lateInstallments,1);a.equal(r.overdueInstallments,1);a.equal(r.averageDelayDays,2);a.equal(r.punctualityRate,50);a.equal(r.balance,100);a.equal(r.trafficLight.color,'yellow');a.equal(JSON.stringify(d),before)});
test('un atraso pequeño aislado queda amarillo y el rojo exige recurrencia o magnitud significativa',()=>{const mild={credits:[credit('cr1',[{date:'2026-09-01',paid:true}])],payments:[payment('p1','cr1',1,'2026-09-02')]};a.equal(summary(mild).trafficLight.color,'yellow');const recurring={credits:[credit('cr1',[{date:'2026-09-01',paid:true},{date:'2026-09-02',paid:true},{date:'2026-09-03',paid:true}])],payments:[payment('p1','cr1',1,'2026-09-03'),payment('p2','cr1',2,'2026-09-04'),payment('p3','cr1',3,'2026-09-06')]};a.equal(summary(recurring).trafficLight.color,'red');a.equal(summary({credits:[credit('cr1',[{date:'2026-08-01'}])],payments:[]}).trafficLight.color,'red')});
test('no atribuye una fecha de pago a cuotas antiguas sin evidencia y conserva finalizado por saldo cero',()=>{const d={credits:[credit('old',[{date:'2026-09-01',paid:true}], 'ACTIVO')],payments:[{id:'old-pay',creditId:'old',amount:100,concept:'CUOTA'}]},r=summary(d);a.equal(r.activeCredits,0);a.equal(r.finishedCredits,1);a.equal(r.paidInstallments,1);a.equal(r.datedPaidInstallments,0);a.equal(r.unknownPaidInstallments,1);a.equal(r.punctualityRate,null);a.equal(r.trafficLight.color,'gray');a.equal(r.trend,null)});
test('un pago parcial no marca cuota cumplida hasta completar su importe',()=>{const d={credits:[credit('cr1',[{date:'2026-09-01',paid:true}])],payments:[payment('p1','cr1',1,'2026-08-31',40),payment('p2','cr1',1,'2026-09-04',60)]},r=summary(d);a.equal(r.datedPaidInstallments,1);a.equal(r.lateInstallments,1);a.equal(r.averageDelayDays,3)});
test('solo presenta tendencia con dos muestras suficientes de cuotas fechadas',()=>{const rows=Array.from({length:6},(_,i)=>({date:`2026-09-0${i+1}`,paid:true})),d={credits:[credit('cr1',rows)],payments:rows.map((q,i)=>payment('p'+i,'cr1',i+1,`2026-09-0${i<3?i+4:i+1}`))},r=summary(d);a.equal(r.trend.direction,'improving');a.equal(r.trend.sampleSize,6);a.equal(summary({credits:[credit('cr1',rows.slice(0,2))],payments:d.payments.slice(0,2)}).trend,null)});
test('un crédito antiguo sin cronograma no se finaliza si aún tiene capital pendiente',()=>{const r=summary({credits:[{id:'old',clientId:'c1',capital:100,principalPaid:25,status:'ACTIVO'}],payments:[]});a.equal(r.activeCredits,1);a.equal(r.finishedCredits,0);a.equal(r.balance,75);a.equal(r.trafficLight.color,'gray')});
test('resume compromisos verificables sin contar cancelados ni cumplimientos por un pago revertido',()=>{const cr=credit('cr1',[{date:'2026-09-01',paid:true},{date:'2026-09-15'}]);cr.paymentPromise={createdAt:'2026-09-02T12:00:00Z',date:'2026-09-03',amount:100,status:'VIGENTE'};cr.paymentPromiseHistory=[{createdAt:'2026-08-01T12:00:00Z',date:'2026-09-01',amount:100,status:'CUMPLIDO',fulfilledByPaymentId:'p1'},{createdAt:'2026-08-02T12:00:00Z',date:'2026-09-01',amount:100,status:'CANCELADO'},{createdAt:'2026-08-03T12:00:00Z',date:'2026-09-02',amount:100,status:'CUMPLIDO',fulfilledByPaymentId:'reverted'}];const d={credits:[cr],payments:[payment('p1','cr1',1,'2026-09-01'),{id:'undo',recordType:'PAYMENT_REVERSAL',reversesPaymentId:'reverted',tombstone:true}]},r=summary(d);a.equal(r.fulfilledPromises,1);a.equal(r.overduePromises,1);a.equal(r.unknownPromises,1);a.equal(r.trafficLight.color,'yellow');a.match(r.trafficLight.reason,/compromiso/i)});
