const assert=require('assert');const F=require('../core/financial-engine'),S=require('../core/schedule-engine'),T=require('../core/transaction-store'),Sync=require('../cloud/operational-sync');function mem(){const db=new Map();return{db,runAtomic:async fn=>fn({get:async p=>db.get(p)||null,set:async(p,v)=>db.set(p,JSON.parse(JSON.stringify(v)))})}}
(async()=>{const a=mem(),store=T.createStore(a),sync=Sync.createOperationalSync({store,actorId:'qa'});
// Alfredo: seed the existing predecessor at version 1, then renew atomically to version 2.
const old={id:'alf-old',clientId:'alf',capital:600,total:720,rate:20,term:1,freq:'monthly',principalPaid:0,interestPaid:0,penaltyPaid:0,status:F.STATUS.ACTIVE,version:1};a.db.set('credits/alf-old',JSON.parse(JSON.stringify(old)));const r=F.interestRenewal(old,{interestAmount:120,newCreditId:'alf-new',paymentId:'alf-pay',date:'2026-09-15',rate:20,term:1,freq:'monthly'});assert.equal(F.principalBalance(r.newCredit),600);r.oldCredit.version=2;r.newCredit.version=1;r.payment.version=1;const input={operationId:'alf-op',type:'INTEREST_RENEWAL',entities:[{collection:'credits',data:r.oldCredit},{collection:'credits',kind:'create',data:r.newCredit},{collection:'payments',kind:'create',data:r.payment}]};assert.equal((await sync.submit(input)).status,'APPLIED');assert.equal((await sync.submit(input)).status,'ALREADY_APPLIED');assert.equal(a.db.get('credits/alf-old').version,2);assert.equal(a.db.get('credits/alf-new').capital,600);assert.equal(a.db.get('payments/alf-pay').concept,F.CONCEPT.INTEREST);
// Elias: real refinance engine. Previous principal balance S/60, new principal S/200 => S/140 cash delivered; with 20% interest total financed is S/240 in four weekly S/60 installments.
const eliasOld={id:'elias-old',clientId:'elias',capital:200,total:240,rate:20,term:4,freq:'weekly',principalPaid:140,interestPaid:0,penaltyPaid:0,status:F.STATUS.ACTIVE,version:1};assert.equal(F.principalBalance(eliasOld),60);const er=F.refinance(eliasOld,{newCapital:200,newCreditId:'elias-new',date:'2026-09-16',rate:20,term:4,freq:'weekly'});assert.equal(er.previousBalance,60);assert.equal(er.cashDisbursed,140);assert.equal(er.newCredit.capital,200);assert.equal(er.newCredit.total,240);const sch=S.generate({total:er.newCredit.total,term:4,freq:'weekly',firstPaymentDate:'2026-09-20'});assert.equal(sch.length,4);sch.forEach(q=>assert.equal(q.amount,60));assert.equal(sch.reduce((n,q)=>n+q.amount,0),240);
// Network/resource exhaustion is queued once even when the same operation is retried.
const queued=[];const fail=Sync.createOperationalSync({store:{execute:async()=>{const e=new Error('RESOURCE_EXHAUSTED');e.code='RESOURCE_EXHAUSTED';throw e}},queue:{enqueue:o=>{if(!queued.some(x=>x.id===o.id))queued.push(o)}}});const net={operationId:'net-op',entities:[{collection:'clients',kind:'create',data:{id:'net-client',version:1}}]};assert.equal((await fail.submit(net)).status,'QUEUED');assert.equal((await fail.submit(net)).status,'QUEUED');assert.equal(queued.length,1);console.log('end-to-end-safety.spec.js PASS')})().catch(e=>{console.error(e);process.exit(1)});

test('renewal UI keeps capital renewal and interest-only renewal separate',()=>{const cards=fs.readFileSync(path.join(__dirname,'../app/operational-cards-v2.js'),'utf8');const actions=fs.readFileSync(path.join(__dirname,'../app/durable-actions-v2.js'),'utf8');expect(cards).toContain("Renovar solo interés','V2UI.renewInterest");expect(cards).toContain("Renovar capital','V2UI.refinance");expect(actions).toContain("renewalInput(c,'INTEREST')");expect(actions).toContain("renewalInput(c,'REFINANCE')");expect(actions).toContain("El monto a renovar no puede ser menor que la deuda pendiente");expect(actions).toContain("DESEMBOLSO_REFINANCIAMIENTO");});
