const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('v2/app/operational-cards-v2.js','utf8');
const document={addEventListener(){},getElementById(){return null}};
const window={addEventListener(){}};
const localStorage={getItem(){return '{}'}};
vm.runInNewContext(code,{window,document,localStorage,alert(){}});
const state=window.MiCarteraV2Cards.installmentState;
const schedule=[{amount:100,balance:60}];
assert.equal(state({status:'ACTIVE',schedule}).collectible,true,'ACTIVE credit with balance must remain collectible');
assert.equal(state({status:'ACTIVO',schedule}).collectible,true,'ACTIVO credit with balance must remain collectible');
assert.equal(state({status:'INACTIVE',schedule}).collectible,false,'inactive credit must never expose collection actions');
assert.equal(state({status:'CANCELLED',schedule}).collectible,false,'cancelled credit must never expose collection actions');
assert.equal(state({status:'ACTIVE',schedule:[{amount:100,balance:0}]}).collectible,false,'fully paid active credit must not be collectible');
assert.equal(state({status:'RENOVADO',schedule}).collectible,false,'renewed historical credit must not expose collection or renewal actions');
const dup=window.MiCarteraV2Cards.duplicateCredits;
const base={id:'cre-a',clientId:'cli-1',status:'ACTIVE',capital:500,total:600,rate:20,term:4,freq:'weekly',firstPaymentDate:'2026-09-20'};
const exact={...base,id:'cre-b'};
const different={...base,id:'cre-c',capital:501};
assert.deepEqual(dup({credits:[base,exact,different]},base).map(x=>x.id),['cre-b'],'only exact active credit signatures must be flagged as duplicates');
assert.deepEqual(dup({credits:[base,{...exact,status:'PAID'}]},base),[],'paid historical credits must never be offered as duplicate consolidation candidates');
const source=fs.readFileSync('v2/app/operational-cards-v2.js','utf8');
assert.ok(source.includes('data-credit-id="${esc(cr.id)}"'),'each rendered credit card must expose its own creditId');
assert.ok(source.includes("button('🔄 Renovar solo interés','MiCarteraV2Cards.renewInterest',cr.id)")&&source.includes("button('♻ Renovar capital','MiCarteraV2Cards.refinance',cr.id)"),'both renewal buttons must pass the selected card creditId');
assert.ok(source.includes("const fn=root.MiCarteraV2DurableActions?.renewInterest")&&source.includes("return fn(id)"),'interest renewal card action must forward the selected creditId');
assert.ok(source.includes("const fn=root.MiCarteraV2DurableActions?.refinance"),'capital renewal card action must forward the selected creditId');
assert.ok(source.includes("type:'CREDIT_DUPLICATE_CONSOLIDATE'")&&source.includes("action:'CREDIT_DUPLICATE_CONSOLIDATED'"),'duplicate credit consolidation must be durable and audited');
assert.ok(source.includes("if(sourcePayments.length||targetPayments.length)throw new Error"),'automatic consolidation must be blocked whenever either credit has payments');
assert.ok(source.includes("collection:'credits',kind:'delete'"),'only the confirmed duplicate credit may be tombstoned');
assert.ok(source.includes("sourceCash=(d.cashMovements||[]).filter(m=>m.ref===source.id)")&&source.includes("targetCash=(d.cashMovements||[]).filter(m=>m.ref===target.id)"),'duplicate consolidation must inspect cash movements for both credits');
assert.ok(source.includes("String(m.concept||'').toUpperCase()==='DESEMBOLSO_CREDITO'")&&source.includes("Math.abs(Number(m.amount||0)-Number(source.capital||0))<0.01"),'cash reconciliation must accept only the expected matching credit disbursement');
assert.ok(source.includes("if((sourceCash.length===1)!==(targetCash.length===1))throw new Error"),'one-sided disbursement must remain blocked to protect cash integrity');
assert.ok(source.includes("collection:'expenses',kind:'delete'")&&source.includes("duplicateCashId:duplicateCash?.id||null"),'safe duplicate consolidation must tombstone and audit only the duplicate disbursement');
assert.ok(source.includes("sourceCash.length>1||targetCash.length>1")&&source.includes('Requiere revisión manual'),'unexpected or multiple cash movements must remain blocked');
console.log('PASS inactive credit actions and safe duplicate-credit controls.');
