const {test}=require('node:test'),a=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
const T=require('../core/transaction-store'),Sync=require('../cloud/operational-sync');
async function setup(){const h=await boot();h.load('core/partner-loans.js');h.load('app/partner-loans-ui.js');const db=new Map();let fail=false;const store=T.createStore({runAtomic:async fn=>{if(fail)throw Error('permission-denied');const staged=new Map(db);const r=await fn({get:async p=>staged.get(p)||null,set:async(p,v)=>staged.set(p,JSON.parse(JSON.stringify(v)))});db.clear();for(const [k,v] of staged)db.set(k,v);return r}});const sync=Sync.createOperationalSync({store,actorId:'test-admin'});h.w.MiCarteraV2SyncBridge.submit=op=>sync.submit(op);h.w.MiCarteraPartners.install();return {...h,db,deny:()=>fail=true}}
const input={id:'loan-a',partner:'Socio QA',date:'2026-09-01',principal:1000,rate:10,firstDue:'2026-10-01'};
function cash(d){return Math.round(d.cashMovements.reduce((n,m)=>n+(m.type==='INGRESO'?m.amount:-m.amount),0)*100)/100}
test('aporte, interés y devolución se contabilizan una vez en caja con auditoría atómica',async()=>{const h=await setup();try{await h.w.MiCarteraPartners.create(input);a.equal(cash(h.get()),1000);await h.w.MiCarteraPartners.interest('loan-a',{date:'2026-10-01',due:'2026-10-01',amount:100});a.equal(cash(h.get()),900);a.equal(h.w.MiCarteraPartnerLoans.balance(h.get().cashMovements[0].partnerLoan),1000);await h.w.MiCarteraPartners.repay('loan-a',{date:'2026-10-02',amount:400,nextMonthlyInterest:60});a.equal(cash(h.get()),500);a.equal(h.w.MiCarteraPartnerLoans.balance(h.get().cashMovements[0].partnerLoan),600);a.equal([...h.db.keys()].filter(k=>k.startsWith('operations/')).length,3);a.equal([...h.db.keys()].filter(k=>k.startsWith('audit/')).length,3);a.equal([...h.db.keys()].filter(k=>k.startsWith('expenses/')).length,2);a.equal(h.db.get('entries/loan-a').amount,1000)}finally{h.close()}});
test('aporte histórico conserva caja previa y no aumenta capital recibido dos veces',async()=>{const h=await setup();try{const d=h.get();d.cashMovements=[{id:'opening',type:'INGRESO',amount:2000}];h.set(d);await h.w.MiCarteraPartners.create({...input,historical:true});a.equal(cash(h.get()),2000);a.equal(h.db.get('entries/loan-a').amount,0);a.equal(h.w.MiCarteraPartnerLoans.balance(h.db.get('entries/loan-a').partnerLoan),1000)}finally{h.close()}});
test('doble aporte e interés repetido se rechazan sin duplicar caja',async()=>{const h=await setup();try{await h.w.MiCarteraPartners.create(input);await a.rejects(h.w.MiCarteraPartners.create({...input,id:'loan-b'}),/Ya existe/);await h.w.MiCarteraPartners.interest('loan-a',{date:'2026-10-01',due:'2026-10-01',amount:100});await a.rejects(h.w.MiCarteraPartners.interest('loan-a',{date:'2026-10-01',due:'2026-10-01',amount:100}),/ya fue pagado/);a.equal(cash(h.get()),900);a.equal([...h.db.keys()].filter(k=>k.startsWith('expenses/')).length,1)}finally{h.close()}});
test('rechazo del servidor conserva todos los saldos y no aplica parcialmente',async()=>{const h=await setup();try{await h.w.MiCarteraPartners.create(input);const before=JSON.stringify(h.get());h.deny();await a.rejects(h.w.MiCarteraPartners.repay('loan-a',{date:'2026-10-02',amount:1000}),/permission-denied/);a.equal(JSON.stringify(h.get()),before);a.equal(h.db.get('entries/loan-a').version,1);a.equal([...h.db.keys()].filter(k=>k.startsWith('expenses/')).length,0)}finally{h.close()}});
test('liquidar varias entregas produce un egreso por entrega y mantiene intereses vencidos',async()=>{const h=await setup();try{await h.w.MiCarteraPartners.create(input);await h.w.MiCarteraPartners.create({...input,id:'loan-b',principal:500,date:'2026-09-02',firstDue:'2026-10-02'});await h.w.MiCarteraPartners.settle(input.partner,'2026-10-03');a.equal(cash(h.get()),0);const loans=h.get().cashMovements.filter(x=>x.partnerLoan);a.equal(loans.length,2);for(const m of loans){a.equal(h.w.MiCarteraPartnerLoans.balance(m.partnerLoan),0);a.equal(h.w.MiCarteraPartnerLoans.due(m.partnerLoan,'2027-01-01').length,1)}a.equal([...h.db.keys()].filter(k=>k.startsWith('expenses/')).length,2)}finally{h.close()}});
