const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),{boot}=require('./dom-harness.cjs');
test('commercial-mobile-5 to candidate install activation reload and local diagnostic preserve the entire pending journal',async()=>{
 const h=await boot();try{
  const w=h.w,key='mi-cartera-v2-cloud-operations:test-admin',journal=JSON.stringify(Array.from({length:4},(_,i)=>({id:'pwa-qa-'+i,operation:{id:'pwa-qa-'+i,operationId:'pwa-qa-'+i,actorId:'test-admin',type:'PAYMENT',createdAt:'2026-10-03T15:32:10Z',writes:[{path:'payments/qa-'+i,kind:'create',data:{id:'qa-'+i,clientId:'c1',date:'2026-10-03',amount:10+i},expectedVersion:0}]},status:['PENDIENTE','ERROR','CONFLICTO','BLOQUEADO'][i],attempts:i,createdAt:'2026-10-03T15:32:10Z',lastError:i?'VERSION_CONFLICT':null,nextAttemptAt:0})),null,2);
  w.localStorage.setItem(key,journal);w.localStorage.setItem('mi-cartera-v2-local-owner','test-admin');const portfolio=w.localStorage.getItem('mi-cartera-v2-validation-state'),cacheMap=new Map();let claims=0;
  async function lifecycle(source){const handlers={},context={Request:class{constructor(url){this.url=url}},URL,console,setTimeout,clearTimeout,localStorage:{getItem:k=>w.localStorage.getItem(k),setItem(){throw Error('SW must not touch journal')},removeItem(){throw Error('SW must not remove journal')},clear(){throw Error('SW must not clear storage')}},caches:{open:async name=>{if(!cacheMap.has(name))cacheMap.set(name,[]);return {addAll:async assets=>cacheMap.get(name).push(...assets)}},keys:async()=>[...cacheMap.keys()],delete:async name=>cacheMap.delete(name)},self:{location:{origin:'https://local.test'},addEventListener:(n,fn)=>handlers[n]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{claims++}}}};vm.runInNewContext(source,context);for(const event of ['install','activate']){let p;handlers[event]({waitUntil:promise=>p=promise});await p;a.equal(w.localStorage.getItem(key),journal,event+' exact journal');a.equal(w.localStorage.getItem('mi-cartera-v2-validation-state'),portfolio,event+' exact portfolio')};return context}
  await lifecycle(fs.readFileSync('v2/tests/fixtures/service-worker-commercial-mobile-5.js','utf8'));a.ok([...cacheMap.keys()].some(k=>k.includes('commercial-mobile-5')));
  await lifecycle(fs.readFileSync('v2/app/service-worker.js','utf8'));a.equal(cacheMap.size,1);a.equal(claims,2);a.equal(w.localStorage.getItem(key),journal);
  let sends=0;w.MiCarteraV2PilotConfig={evaluate:()=>({ready:true})};w.MiCarteraV2FirestoreAdapter={createFirestoreAtomicAdapter:()=>({})};w.MiCarteraV2Store={createStore:()=>({execute:async()=>{sends++;return {status:'APPLIED'}}})};
  for(const p of ['core/sync-errors.js','core/offline-operation-queue.js','cloud/operational-sync.js','app/operation-sync-bridge.js','cloud/runtime-cloud.js'])h.load(p);
  const runtime=w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});w.dispatchEvent(new w.CustomEvent('online'));a.equal((await runtime.flush()).status,'REVIEW_REQUIRED');h.load('app/pending-review-v2.js');w.MiCarteraV2PendingReview.open();a.equal(w.document.querySelectorAll('[data-rows] > .card').length,4);a.equal(sends,0);a.equal(w.localStorage.getItem(key),journal);a.equal(w.localStorage.getItem('mi-cartera-v2-validation-state'),portfolio);a.equal(w.MiCarteraV2PendingReview.snapshot().journals[key],journal);
 }finally{h.close()}
});
