const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('fs'),vm=require('vm');
function boot(withPending=true,count=4){
 const key='mi-cartera-v2-cloud-operations:qa-redmi',journal=JSON.stringify(Array.from({length:count},(_,i)=>({id:'fictional-'+i,status:['PENDIENTE','ERROR','CONFLICTO','BLOQUEADO'][i],attempts:i,nextAttemptAt:0,createdAt:'2026-10-03T14:00:00Z',operation:{id:'fictional-'+i,operationId:'fictional-'+i,actorId:'qa-redmi',type:'PAYMENT',writes:[{kind:'create',path:'payments/fictional-'+i,data:{id:'fictional-'+i,amount:7+i},expectedVersion:0}]}})),null,2);
 const data=new Map(withPending?[[key,journal]]:[]),timers=[],listeners={};let calls=0;
 const storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),key:i=>[...data.keys()][i],get length(){return data.size}};
 const c={console,localStorage:storage,navigator:{onLine:true},setTimeout:(f,ms)=>{if(ms===0){timers.push(f);return 0}return setTimeout(f,ms)},clearTimeout,setInterval(){},document:{visibilityState:'visible',addEventListener(){},getElementById:()=>null,createElement:()=>({style:{}}),querySelector:()=>({insertBefore(){}})},CustomEvent:class{constructor(type,init){this.type=type;this.detail=init?.detail}},addEventListener:(n,f)=>(listeners[n]??=[]).push(f),removeEventListener(){},dispatchEvent:e=>(listeners[e.type]||[]).forEach(f=>f(e))};c.window=c;
 c.MiCarteraV2VersionGuard={requireReady(){}};c.MiCarteraV2AuthCloudGate={requireReady:()=>({uid:'qa-redmi',role:'admin'}),state:()=>({ready:true,uid:'qa-redmi',role:'admin'})};c.MiCarteraV2PilotConfig={evaluate:()=>({ready:true})};c.MiCarteraV2FirestoreAdapter={createFirestoreAtomicAdapter:()=>({})};c.MiCarteraV2Store={createStore:()=>({execute:async()=>{calls++;return {status:'APPLIED'}}})};
 vm.createContext(c);const load=p=>vm.runInContext(fs.readFileSync('v2/'+p,'utf8'),c,{filename:p});
 for(const p of ['core/sync-errors.js','core/offline-operation-queue.js','cloud/operational-sync.js','app/operation-sync-bridge.js','cloud/runtime-cloud.js'])load(p);
 const runtime=c.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});
 return {c,load,runtime,timers,key,journal,storage,calls:()=>calls};
}
test('four preexisting journal entries remain exact through startup online focus timer and explicit flush',async()=>{
 const h=boot();h.load('app/sync-status-ui.js');for(const f of h.timers)await f();h.c.dispatchEvent(new h.c.CustomEvent('online'));h.c.dispatchEvent(new h.c.CustomEvent('focus'));await new Promise(r=>setImmediate(r));
 a.equal((await h.runtime.flush()).status,'REVIEW_REQUIRED');a.equal(h.calls(),0);a.equal(h.storage.getItem(h.key),h.journal);a.equal(h.c.MiCarteraV2SyncBridge.status().reviewRequired,true);
 await a.rejects(h.c.MiCarteraV2SyncBridge.submit({operationId:'new',type:'PAYMENT',entities:[{collection:'payments',kind:'create',data:{id:'new',amount:1}}]}),/pendientes.*revisión|REVIEW_REQUIRED/i);a.equal(h.calls(),0);a.equal(h.storage.getItem(h.key),h.journal);
});
test('a device with no preexisting pending journal keeps normal online acceptance',async()=>{const h=boot(false);const r=await h.c.MiCarteraV2SyncBridge.submit({operationId:'fresh',type:'PAYMENT',entities:[{collection:'payments',kind:'create',data:{id:'fresh',amount:1}}]});a.equal(r.status,'APPLIED');a.equal(h.calls(),1);a.equal(h.c.MiCarteraV2SyncBridge.status().reviewRequired,false)});

test('two protected receipts release only after exact explicit confirmation and a fresh fictional payment does not replay them',async()=>{const h=boot(true,2),c=h.c,T=require('../core/transaction-store.js');c.MiCarteraV2Store.fingerprint=T.fingerprint;c.navigator.locks={request:async(_n,_o,fn)=>fn()};c.firestoreV2={db:{},doc:(_d,...p)=>p,getDocFromServer:async p=>{const row=JSON.parse(h.journal).find(x=>x.id===p.at(-1)),op=row.operation;return {exists:()=>true,data:()=>({id:op.id,actorId:op.actorId,type:op.type,status:'APPLIED',fingerprint:T.fingerprint(op),appliedAt:'2026-10-03T15:30:00Z'})}}};h.load('app/pending-review-v2.js');await c.MiCarteraV2PendingReview.check();a.equal(c.MiCarteraV2SyncBridge.status().reviewRequired,true);a.equal(h.storage.getItem(h.key),h.journal);await c.MiCarteraV2PendingReview.confirmApplied();a.equal(h.calls(),0,'confirming must never execute either protected receipt');a.equal(c.MiCarteraV2SyncBridge.status().reviewRequired,false);const r=await c.MiCarteraV2SyncBridge.submit({operationId:'fresh-fictional',type:'PAYMENT',entities:[{collection:'payments',kind:'create',data:{id:'fresh-fictional',amount:90}}]});a.equal(r.status,'APPLIED');a.equal(h.calls(),1,'only the new fictitious operation can be executed');const after=JSON.parse(h.storage.getItem(h.key));a.equal(after.length,3);for(let i=0;i<2;i++){a.equal(after[i].status,'SINCRONIZADO');a.deepEqual(after[i].operation,JSON.parse(h.journal)[i].operation)}});
test('removing a protected journal row or confirming only one cannot unlock new acceptance',async()=>{for(const missing of [false,true]){const h=boot(true,2),rows=JSON.parse(h.journal);rows[0].status='SINCRONIZADO';if(missing)rows.pop();h.storage.setItem(h.key,JSON.stringify(rows));a.equal(h.c.MiCarteraV2SyncBridge.status().reviewRequired,true);await a.rejects(h.c.MiCarteraV2SyncBridge.submit({operationId:'new',type:'PAYMENT',entities:[]}),/pendientes.*revisión/);a.equal(h.calls(),0)}});
