const {test}=require('node:test'),a=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
const form=(h,phone,name='Cliente nuevo')=>{for(const [id,value] of Object.entries({fName:name,fPhone:phone,fDni:'',fAddress:'Dirección ficticia',fRoute:'pruebas'}))h.w.document.getElementById(id).value=value};
function modules(h){h.load('app/customer-experience-v2.js');h.load('app/client-edit-v2.js');h.w.MiCarteraV2ClientEditor.install()}
test('new client rejects an existing national phone entered with +51 or 0051',async()=>{const h=await boot();try{modules(h);const before=JSON.stringify(h.get());for(const phone of ['+51 999 111 222','0051 (999) 111-222']){form(h,phone);await h.w.MiCarteraV2WriteActions.addClient();a.equal(h.commits.length,0,h.alerts.join());a.equal(JSON.stringify(h.get()),before)}a.equal(h.alerts.length,2)}finally{h.close()}});
test('active editor rejects another client phone in equivalent international format',async()=>{const h=await boot();try{modules(h);const d=h.get();d.clients.push({id:'c2',name:'Segundo ficticio',phone:'999333444'});h.set(d);h.w.MiCarteraV2ClientEditor.openEdit('c2');h.w.document.getElementById('fPhone').value='0051 999111222';await h.w.MiCarteraV2ClientEditor.updateClient();a.equal(h.commits.length,0);a.deepEqual(h.get(),d);a.match(h.alerts.join(),/Ya existe/)}finally{h.close()}});
test('late window load keeps client edit mode and saving cannot become a create',async()=>{const h=await boot();try{modules(h);h.w.document.dispatchEvent(new h.w.Event('DOMContentLoaded'));h.w.dispatchEvent(new h.w.Event('load'));h.w.MiCarteraV2ClientEditor.openEdit('c1');h.w.document.getElementById('fAddress').value='Dirección corregida';await h.w.document.getElementById('saveClient').onclick();a.equal(h.commits.length,1,h.alerts.join());a.equal(h.commits[0].type,'CLIENT_UPDATE');a.equal(h.get().clients.length,1);a.equal(h.get().clients[0].address,'Dirección corregida');a.equal(h.w.document.getElementById('clientForm').dataset.editId,undefined);a.equal(h.w.document.getElementById('fName').dataset.clientId,undefined)}finally{h.close()}});
test('equivalent phone duplicate can consolidate while keeping credit and payment identities',async()=>{const h=await boot();try{modules(h);const d=h.get();d.clients[0].customData={keep:true};d.clients.push({id:'c2',name:'Segundo ficticio',phone:'0051 999 111 222',location:'-12,-77'});d.credits=[{id:'cr2',clientId:'c2',version:1,capital:100}];d.payments=[{id:'p2',creditId:'cr2',amount:10}];h.set(d);a.equal(await h.w.MiCarteraV2ClientEditor.mergeDuplicateClient('c2','c1'),true,h.alerts.join());const next=h.get();a.equal(next.clients.length,1);a.equal(next.clients[0].phone,'999111222');a.equal(next.clients[0].location,'-12,-77');a.deepEqual(next.clients[0].customData,{keep:true});a.equal(next.credits[0].clientId,'c1');a.equal(next.credits[0].id,'cr2');a.deepEqual(next.payments,d.payments);a.equal(h.commits[0].entities.length,3)}finally{h.close()}});
test('equivalent phone duplicate exposes consolidation and blocks standalone delete',async()=>{const h=await boot();try{modules(h);const d=h.get();d.clients.push({id:'c2',name:'Duplicado ficticio',phone:'+51 999111222'});h.set(d);h.w.document.getElementById('clientsList').innerHTML='<div data-client-card data-client-id="c1"></div>';h.w.MiCarteraV2ClientEditor.decorate();a.ok(h.w.document.querySelector('.v2-merge-client-button'));await h.w.MiCarteraV2ClientEditor.deleteClient('c1');a.equal(h.commits.length,0);a.deepEqual(h.get(),d)}finally{h.close()}});
test('WhatsApp normalization is equivalent for Peru formats and preserves explicit foreign code',async()=>{const h=await boot();try{modules(h);const opened=[];h.w.open=url=>opened.push(url);for(const phone of ['999111222','+51 999111222','0051 999111222'])h.w.MiCarteraV2CustomerExperience.whatsapp({phone},'Prueba aislada');for(const url of opened)a.match(url,/^https:\/\/wa\.me\/51999111222\?text=Prueba%20aislada$/);h.w.MiCarteraV2CustomerExperience.whatsapp({phone:'+353123456'},'Prueba');a.match(opened[3],/^https:\/\/wa\.me\/353123456\?/);a.equal(h.commits.length,0)}finally{h.close()}});
