const {test}=require('node:test'),a=require('node:assert/strict'),{boot,KEY}=require('./dom-harness.cjs');
const uid='test-admin',key='mi-cartera-v2-cloud-operations:'+uid;
const payment=(id,credit='qa-credit-new')=>({operationId:id,type:'PAYMENT',entities:[{collection:'payments',kind:'create',data:{id:'pay-'+id,creditId:credit,amount:9,version:1}},{collection:'entries',kind:'create',data:{id:'cash-'+id,type:'INGRESO',amount:9,ref:'pay-'+id,version:1}},{collection:'credits',kind:'set',data:{id:credit,clientId:'c1',version:2,total:90,principalPaid:9}}]});
async function fixture(){
 const h=await boot(),w=h.w;Object.defineProperty(w.navigator,'locks',{value:{request:async(_n,_o,fn)=>fn({})},configurable:true});
 for(const f of ['core/transaction-store.js','core/sync-errors.js','core/offline-operation-queue.js','cloud/operational-sync.js'])h.load(f);
 const nativeCreateStore=w.MiCarteraV2Store.createStore;
 const rows=Array.from({length:6},(_,i)=>({id:'qa-existing-'+i,status:i?'PENDIENTE':'ERROR',attempts:i?0:1,nextAttemptAt:0,createdAt:'2026-10-03T15:00:00Z',lastError:i?null:'HTTP 429',operation:{id:'qa-existing-'+i,operationId:'qa-existing-'+i,type:'PAYMENT',actorId:uid,writes:[{kind:'create',path:'payments/qa-existing-'+i,data:{id:'qa-existing-'+i,amount:10,creditId:'qa-old-credit-'+i},expectedVersion:0}]}}));
 const closed=Array.from({length:2},(_,i)=>({id:'qa-closed-'+i,status:'CERRADO_ADMIN',attempts:2,operation:{id:'qa-closed-'+i,operationId:'qa-closed-'+i,type:'PAYMENT',actorId:uid,writes:[{kind:'create',path:'payments/qa-closed-'+i,data:{id:'qa-closed-'+i,amount:10},expectedVersion:0}]},administrativeClosure:{noReplay:true,serverApplied:'NOT_VERIFIED',actorId:uid,confirmedAt:'2026-10-03T16:00:00Z',reference:'QA_ADMIN_CLOSED',reason:'CLOUD_HTTP_429'}}));
 const raw=JSON.stringify(closed.concat(rows),null,2),ledger=JSON.stringify(closed),ledgerKey=w.MiCarteraV2OfflineQueue.ledgerKey(key);w.localStorage.setItem(key,raw);w.localStorage.setItem(ledgerKey,ledger);w.localStorage.setItem('mi-cartera-v2-local-owner',uid);
 let reads=0,sends=0,mode='quota',proofs=new Set();w.firestoreV2={db:{},doc:(_d,...p)=>p,getDoc:async()=>{throw Object.assign(Error('HTTP 429'),{code:429})},getDocFromServer:async p=>{reads++;if(mode==='quota')throw Object.assign(Error('HTTP 429'),{code:429});const row=JSON.parse(w.localStorage.getItem(key)).find(x=>x.id===p.at(-1));return {exists:()=>proofs.has(row.id),data:()=>({id:row.id,type:row.operation.type,actorId:uid,status:'APPLIED',fingerprint:w.MiCarteraV2Store.fingerprint(row.operation),appliedAt:'2026-10-03T17:00:00Z'})}}};
 h.load('app/pending-review-v2.js');w.MiCarteraV2PilotConfig={evaluate:()=>({ready:true})};w.MiCarteraV2FirestoreAdapter={createFirestoreAtomicAdapter:()=>({})};w.MiCarteraV2Store.createStore=()=>({execute:async()=>{sends++;return {status:'APPLIED'}}});
 for(const f of ['core/commercial-model.js','app/commercial-actions-v2.js','app/operation-sync-bridge.js','cloud/runtime-cloud.js'])h.load(f);const runtime=w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});
 return {...h,rows,raw,closed,ledger,ledgerKey,runtime,nativeCreateStore,reads:()=>reads,sends:()=>sends,server:(value,ids=[])=>{mode=value;proofs=new Set(ids)}};
}
test('server reconciliation acknowledges only exact matches, keeps missing rows and never resends any of eight original records',async()=>{const h=await fixture();try{
 h.server('available',['qa-existing-0','qa-existing-2']);const business=h.w.localStorage.getItem(KEY);const r=await h.w.MiCarteraV2PendingReview.reconcile();a.equal(r.confirmed,2);a.equal(r.pending,4);a.equal(h.sends(),0);a.equal(h.w.localStorage.getItem(KEY),business);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);a.equal(h.w.localStorage.getItem(r.backupKey),h.raw);
 const after=JSON.parse(h.w.localStorage.getItem(key));after.forEach((x,i)=>{a.deepEqual(x.operation,JSON.parse(h.raw)[i].operation);if(i<2)a.deepEqual(x,JSON.parse(h.raw)[i]);if(i>=2&&![2,4].includes(i))a.deepEqual(x,JSON.parse(h.raw)[i])});
 await h.runtime.flush();a.equal(h.sends(),0);a.equal(h.w.MiCarteraV2PendingReview.pending().length,4);
}finally{h.close()}});
test('a Cloud content collision blocks only that credit even when the original local status was pending',async()=>{const h=await fixture();try{
 h.server('available',h.rows.map(x=>x.id));const read=h.w.firestoreV2.getDocFromServer;h.w.firestoreV2.getDocFromServer=async p=>{const doc=await read(p);return {...doc,data:()=>({...doc.data(),fingerprint:'wrong-content'})}};
 await h.w.MiCarteraV2PendingReview.reconcile();await a.rejects(()=>h.w.MiCarteraV2SyncBridge.submit(payment('qa-collision-credit','qa-old-credit-0')),/revisión|CONFLICT/i);a.equal(h.w.localStorage.getItem(key),h.raw);const r=await h.w.MiCarteraV2SyncBridge.submit(payment('qa-unrelated'));a.equal(r.status,'QUEUED');a.equal(h.sends(),0);
}finally{h.close()}});
test('reloading a reader cannot bypass the owner-scoped Cloud quota pause',async()=>{const h=await fixture();try{
 await h.w.MiCarteraV2PendingReview.reconcile();a.equal(h.reads(),1);h.load('app/pending-review-v2.js');await h.w.MiCarteraV2PendingReview.reconcile();a.equal(h.reads(),1);a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);
}finally{h.close()}});
test('a fresh operation ID cannot recreate protected payment or cash identifiers',async()=>{const h=await fixture();try{
 const input=payment('qa-recreation');input.entities[0].data.id='qa-existing-0';const source=h.w.localStorage.getItem(key);await a.rejects(()=>h.w.MiCarteraV2SyncBridge.submit(input),/revisión|COLLISION/i);a.equal(h.w.localStorage.getItem(key),source);a.equal(h.sends(),0);
}finally{h.close()}});
test('quota circuit stops at one server read, preserves every byte and keeps automatic send blocked',async()=>{const h=await fixture();try{
 const r=await h.runtime.flush();a.equal(r.status,'REVIEW_REQUIRED');a.equal(h.reads(),1);await h.runtime.flush();a.equal(h.reads(),1);a.equal(h.sends(),0);a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);
}finally{h.close()}});
test('the local read-only view pauses background acknowledgement while explicit checks keep every journal byte intact',async()=>{const h=await fixture();try{
 h.server('available',h.rows.map(x=>x.id));h.w.MiCarteraV2PendingReview.open();await h.runtime.flush();a.equal(h.reads(),0);a.equal(h.w.localStorage.getItem(key),h.raw);const panel=h.w.document.getElementById('v2PendingReview');await panel.querySelector('[data-check]').onclick();a.equal(h.reads(),6);a.equal(h.w.localStorage.getItem(key),h.raw);a.match(panel.querySelector('[data-confirm-status]').textContent,/6 confirmadas/);panel.remove();await h.w.MiCarteraV2PendingReview.reconcile({force:true});a.equal(h.w.MiCarteraV2PendingReview.pending().length,0);a.equal(h.sends(),0);
}finally{h.close()}});
test('six protected rows do not block a distinct new durable incoming collection and cannot be replayed after reload',async()=>{const h=await fixture();try{
 const r=await h.w.MiCarteraV2OperationCommitGate.submit({bridge:h.w.MiCarteraV2SyncBridge,versionGuard:h.w.MiCarteraV2VersionGuard,authGate:h.w.MiCarteraV2AuthCloudGate,operation:payment('qa-new-collection')});a.equal(r.status,'QUEUED');a.equal(r.durable,true);a.equal(h.sends(),0);const after=JSON.parse(h.w.localStorage.getItem(key));a.equal(after.length,9);a.deepEqual(after.slice(0,8),JSON.parse(h.raw));a.equal(after.at(-1).reviewBeforeSend,true);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);
 h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});await h.runtime.flush();a.equal(h.sends(),0);
}finally{h.close()}});
test('a blocked credit isolates its own collections without globally preventing unrelated incoming collections',async()=>{const h=await fixture();try{
 const rows=JSON.parse(h.raw);rows[2].status='CONFLICTO';rows[2].operation.writes.push({kind:'set',path:'credits/qa-old-credit-0',expectedVersion:1,data:{id:'qa-old-credit-0',version:2}});h.w.localStorage.setItem(key,JSON.stringify(rows));
 const gate=h.w.MiCarteraV2OperationCommitGate,submit=op=>gate.submit({bridge:h.w.MiCarteraV2SyncBridge,versionGuard:h.w.MiCarteraV2VersionGuard,authGate:h.w.MiCarteraV2AuthCloudGate,operation:op});
 await a.rejects(()=>submit(payment('qa-same-credit','qa-old-credit-0')),/revisión|CONFLICT/i);const source=h.w.localStorage.getItem(key);await a.rejects(()=>submit({...payment('qa-outflow'),type:'CREDIT_RENEW'}),/revisión|REVIEW/i);a.equal(h.w.localStorage.getItem(key),source);const accepted=await submit(payment('qa-other-credit'));a.equal(accepted.status,'QUEUED');a.equal(h.sends(),0);
}finally{h.close()}});
test('same-id collision and closed administrative original cannot be accepted as a new collection',async()=>{const h=await fixture();try{
 for(const id of ['qa-closed-0','qa-existing-0'])await a.rejects(()=>h.w.MiCarteraV2SyncBridge.submit(payment(id)),/CLOSED|COLLISION|revisión/i);a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.sends(),0);
}finally{h.close()}});
test('Cloud marker with a wrong type or invalid acknowledgement date cannot confirm a journal row',async()=>{for(const mode of ['type','date']){const h=await fixture();try{
 h.server('available',h.rows.map(x=>x.id));const read=h.w.firestoreV2.getDocFromServer;h.w.firestoreV2.getDocFromServer=async p=>{const doc=await read(p);return {...doc,data:()=>({...doc.data(),...(mode==='type'?{type:'CREDIT_CREATE'}:{appliedAt:'invalid'})})}};
 const proofs=await h.w.MiCarteraV2PendingReview.check();a.equal(proofs.filter(x=>x.cloudStatus==='CONFIRMED').length,0);a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.sends(),0);
}finally{h.close()}}});
test('a lost delivery reply is reconciled against the real atomic marker without executing the payment twice',async()=>{const h=await fixture();try{
 h.w.localStorage.setItem(key,JSON.stringify(h.closed));const remote=new Map(),buffered=[];let transactions=0;h.w.MiCarteraV2Store.createStore=h.nativeCreateStore;
 h.w.MiCarteraV2FirestoreAdapter.createFirestoreAtomicAdapter=()=>({runAtomic:async action=>{transactions++;const result=await action({get:async path=>remote.get(path),set:async(path,value)=>buffered.push([path,structuredClone(value)])});for(const [path,value] of buffered)remote.set(path,value);return new Promise(()=>{})}});
 h.w.firestoreV2.getDocFromServer=async p=>({exists:()=>remote.has('operations/'+p.at(-1)),data:()=>remote.get('operations/'+p.at(-1))});const timeout=h.w.setTimeout;h.w.setTimeout=(fn,ms)=>timeout(fn,ms===4000?5:ms);
 const input=payment('qa-lost-reply');input.entities=input.entities.filter(e=>e.collection!=='credits');input.entities.forEach(e=>e.data.workerId='qa-worker');h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});
 const r=await h.w.MiCarteraV2SyncBridge.submit(input);a.equal(r.status,'QUEUED');a.equal(remote.get('payments/pay-qa-lost-reply').amount,9);const result=await h.runtime.flush();a.equal(result.status,'RECONCILED');a.equal(transactions,1);a.equal(JSON.parse(h.w.localStorage.getItem(key)).at(-1).status,'SINCRONIZADO');a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);
}finally{h.close()}});
test('the replacement runtime invalidates old flush handles even with the same owner and verified version',async()=>{const h=await fixture();try{const old=h.runtime;h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});await a.rejects(()=>old.flush(),/RUNTIME_REPLACED/);a.equal(h.sends(),0);a.equal(h.w.localStorage.getItem(key),h.raw)}finally{h.close()}});
test('closed payment identifiers cannot be recreated under a fresh operation ID even without a review hold',async()=>{const h=await fixture();try{
 h.w.localStorage.setItem(key,JSON.stringify(h.closed));h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});a.equal(h.w.MiCarteraV2SyncBridge.status().reviewRequired,false);const source=h.w.localStorage.getItem(key),input=payment('qa-renamed-closed');input.entities[0].data.id='qa-closed-0';input.entities.forEach(e=>e.data.workerId='qa-worker');await a.rejects(()=>h.w.MiCarteraV2SyncBridge.submit(input),/COLLISION|identificador/i);a.equal(h.w.localStorage.getItem(key),source);a.equal(h.sends(),0);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);
}finally{h.close()}});
test('upgrading the approved PWA preserves all six protected payloads, two administrative closures, backup and financial state',async()=>{const h=await fixture();try{
 const fs=require('node:fs'),vm=require('node:vm'),cache=new Map(),business=h.w.localStorage.getItem(KEY);h.w.localStorage.setItem('qa-original-recovery-copy',h.raw);
 for(const file of ['v2/tests/fixtures/service-worker-unified-share-1.js','v2/app/service-worker.js']){const handlers={},c={Request:class{constructor(url){this.url=url}},URL,setTimeout,clearTimeout,localStorage:{setItem(){throw Error('SW must not alter journal')},removeItem(){throw Error('SW must not erase journal')},clear(){throw Error('SW must not clear storage')}},caches:{open:async name=>{cache.set(name,[]);return {addAll:async values=>cache.get(name).push(...values)}},keys:async()=>[...cache.keys()],delete:async name=>cache.delete(name)},self:{addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}},location:{origin:'https://local.test'}}};vm.runInNewContext(fs.readFileSync(file,'utf8'),c);for(const event of ['install','activate']){let pending;handlers[event]({waitUntil:p=>pending=p});await pending;a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.w.localStorage.getItem(h.ledgerKey),h.ledger);a.equal(h.w.localStorage.getItem(KEY),business);a.equal(h.w.localStorage.getItem('qa-original-recovery-copy'),h.raw)}}
 a.equal(cache.size,1);h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});await h.runtime.flush();h.w.MiCarteraV2PendingReview.open();a.equal(h.w.document.querySelectorAll('[data-rows] > .card').length,8);a.equal(h.w.localStorage.getItem(key),h.raw);a.equal(h.sends(),0);
}finally{h.close()}});
test('a stale online tab cannot send fresh-looking pending rows introduced by another tab or restored journal',async()=>{const h=await fixture();try{
 h.w.localStorage.setItem(key,JSON.stringify(h.closed));h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});a.equal(h.w.MiCarteraV2SyncBridge.status().reviewRequired,false);
 const restored=JSON.stringify(h.closed.concat(h.rows.map(x=>({...x,status:'PENDIENTE',attempts:0,lastError:null}))));h.w.localStorage.setItem(key,restored);
 a.equal(h.w.MiCarteraV2SyncBridge.status().reviewRequired,true);await h.runtime.flush();a.equal(h.sends(),0);a.equal(h.w.localStorage.getItem(key),restored);
}finally{h.close()}});
test('identity or version changes while preparing a new cash guard stop the transaction before any financial write',async()=>{for(const mode of ['version','actor']){const h=await fixture();try{
 h.w.localStorage.setItem(key,'[]');h.runtime=h.w.MiCarteraV2CloudRuntime.configure({orgId:'v2-mi-cartera-pilot'});h.w.MiCarteraV2CommercialActions.prepareQueuedOperation=async op=>{if(mode==='version')h.w.MiCarteraV2VersionGuard.requireReady=()=>{throw Error('V2_VERSION_NOT_READY')};else h.w.MiCarteraV2AuthCloudGate.requireReady=()=>({uid:'another-actor',role:'admin'});const copy={...op,writes:op.writes.concat({kind:'create',path:'routes/leader-cash-revision',expectedVersion:0,data:{id:'leader-cash-revision',version:1}})};delete copy.requiresLeaderCashRevision;return copy};
 const input={...payment('qa-guard-change'),requiresLeaderCashRevision:true};input.entities.forEach(e=>e.data.workerId='qa-worker');await h.w.MiCarteraV2SyncBridge.submit(input);await h.runtime.flush();a.equal(h.sends(),0);a.notEqual(JSON.parse(h.w.localStorage.getItem(key))[0].status,'SINCRONIZADO');
}finally{h.close()}}});
