const {test}=require('node:test'),a=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
async function setup(){const h=await boot(),d=h.get();d.credits=[
 {id:'chain-origin',clientId:'c1',capital:500,total:550,status:'RENOVADO',renewedTo:'chain-successor',version:2,schedule:[{amount:550,balance:550,date:'2026-10-01'}]},
 {id:'chain-successor',clientId:'c1',capital:800,total:880,rate:10,term:2,freq:'weekly',status:'ACTIVO',originCreditId:'chain-origin',renewedFrom:'chain-origin',originDebt:550,renewalMode:'REFINANCE',version:1,schedule:[{amount:440,balance:440,date:'2026-10-08'},{amount:440,balance:440,date:'2026-10-15'}]}
];d.cashMovements=[{id:'net-cash',type:'EGRESO',amount:250,concept:'DESEMBOLSO_REFINANCIAMIENTO',ref:'chain-successor',version:1}];h.set(d);h.load('app/operational-cards-v2.js');return h}
test('generic deletion of an unpaid renewal preserves its predecessor, debt, cash and history',async()=>{const h=await setup();try{const before=JSON.stringify(h.get());await h.w.MiCarteraV2Cards.deleteCredit('chain-successor');a.equal(JSON.stringify(h.get()),before);a.equal(h.commits.length,0);a.match(h.alerts.at(-1),/renovación/i)}finally{h.close()}});
test('a renewal card keeps collection and detail but never offers generic deletion or duplicate consolidation',async()=>{const h=await setup();try{h.w.MiCarteraV2Cards.render();const card=h.w.document.querySelector('[data-credit-id="chain-successor"]');a.match(card.textContent,/Cobrar/);a.match(card.textContent,/detalle/);a.doesNotMatch(card.textContent,/Eliminar crédito|Revisar duplicado/)}finally{h.close()}});
test('reverse links and duplicate consolidation cannot detach a renewal chain',async()=>{const h=await setup();try{const d=h.get();const cr=d.credits[1];delete cr.originCreditId;delete cr.renewedFrom;delete cr.renewalMode;d.credits.push({...cr,id:'unlinked-copy'});d.cashMovements=[];h.set(d);const before=JSON.stringify(h.get());await h.w.MiCarteraV2Cards.deleteCredit('chain-successor');a.equal(JSON.stringify(h.get()),before);await h.w.MiCarteraV2Cards.consolidateDuplicateCredit('chain-successor','unlinked-copy');a.equal(JSON.stringify(h.get()),before);a.equal(h.commits.length,0);a.match(h.alerts.at(-1),/renovación/i)}finally{h.close()}});
test('a standalone unpaid credit with a disbursement is retained to protect cash history',async()=>{const h=await setup();try{const d=h.get();d.credits=[{id:'standalone',clientId:'c1',capital:300,total:330,status:'ACTIVO',version:1}];d.cashMovements=[{id:'cash-standalone',ref:'standalone',type:'EGRESO',amount:300,concept:'DESEMBOLSO_CREDITO',version:1},{id:'unrelated',type:'INGRESO',amount:1000}];h.set(d);const before=JSON.stringify(h.get());await h.w.MiCarteraV2Cards.deleteCredit('standalone');a.equal(h.commits.length,0);a.equal(JSON.stringify(h.get()),before);a.match(h.alerts.at(-1),/historial de caja/i)}finally{h.close()}});
