const {test}=require('node:test'),a=require('node:assert/strict'),{boot}=require('./dom-harness.cjs');
async function open(){const h=await boot(),d=h.get();d.credits=[{id:'fifth-fixture',clientId:'c1',capital:600,total:720,rate:20,term:12,freq:'daily',status:'ACTIVO',version:1,principalPaid:150,interestPaid:30,schedule:[{date:'2026-10-09',amount:720,balance:540,paid:180}]}];h.set(d);const done=h.w.MiCarteraV2RenewalActions.refinance('fifth-fixture');const set=(id,value)=>{const e=h.w.document.getElementById(id);e.value=value;e.dispatchEvent(new h.w.Event('change'))};set('v2RenewDate','2026-10-02');set('v2RenewFirstDate','2026-10-09');set('v2RenewTerm','4');set('v2RenewFreq','weekly');return {...h,done,set}}
test('four weekly renewal installments expose the fifth input and preview conserves total and cash without registering',async()=>{
 const h=await open();try{const before=JSON.stringify(h.get()),box=h.w.document.getElementById('v2RenewExtraBox');a.equal(box.style.display,'block');a.match(box.textContent,/5.ª cuota adicional/);h.set('v2RenewExtraAmount','320');h.set('v2RenewExtraDate','2026-11-06');a.match(h.w.document.getElementById('v2RenewExtraSummary').textContent,/4 cuotas normales de S\/ 100.00/);a.equal(h.w.document.getElementById('v2RenewTotal').textContent,'S/ 720.00');a.equal(h.w.document.getElementById('v2RenewNet').textContent,'S/ 60.00');a.equal(h.w.document.getElementById('v2RenewMaturity').value,'2026-11-06');h.w.document.getElementById('v2RenewReview').click();a.match(h.w.document.getElementById('v2RenewalReview').textContent,/5.ª cuota adicional: S\/ 320.00/);a.equal(JSON.stringify(h.get()),before);a.equal(h.commits.length,0);h.w.document.getElementById('v2ReviewBack').click();h.w.document.getElementById('v2RenewCancel').click();await h.done;a.equal(h.w.MiCarteraV2OperationCommitGate.isActionRunning(),false)}finally{h.close()}
});
test('a confirmed fictitious renewal stores four equal regular installments plus the extra within the original total',async()=>{
 const h=await open();try{h.set('v2RenewExtraAmount','320');h.set('v2RenewExtraDate','2026-11-06');h.w.document.getElementById('v2RenewReview').click();const accepted=h.w.document.getElementById('v2RenewAccepted');accepted.checked=true;accepted.onchange();h.w.document.getElementById('v2ConfirmRenewal').click();await h.done;const d=h.get(),c=d.credits.at(-1);a.equal(h.commits.length,1);a.equal(c.total,720);a.deepEqual(c.schedule.filter(x=>!x.extra).map(x=>x.amount),[100,100,100,100]);a.equal(c.schedule.find(x=>x.extra).amount,320);a.equal(c.schedule.reduce((n,x)=>n+x.amount,0),720);a.equal(c.netDisbursement,60);a.equal(d.cashMovements.reduce((n,x)=>n+(x.type==='EGRESO'?-x.amount:x.amount),0),-60)}finally{h.close()}
});
test('the additional installment stays optional and changing frequency excludes it from the proposal',async()=>{
 const h=await open();try{h.set('v2RenewExtraAmount','320');h.set('v2RenewExtraDate','2026-11-06');h.set('v2RenewFreq','daily');a.equal(h.w.document.getElementById('v2RenewExtraBox').style.display,'none');h.w.document.getElementById('v2RenewReview').click();a.doesNotMatch(h.w.document.getElementById('v2RenewalReview').textContent,/5.ª cuota adicional:/);a.equal(h.commits.length,0);h.w.document.getElementById('v2ReviewBack').click();h.set('v2RenewFreq','weekly');h.set('v2RenewExtraAmount','');h.w.document.getElementById('v2RenewReview').click();const accepted=h.w.document.getElementById('v2RenewAccepted');accepted.checked=true;accepted.onchange();h.w.document.getElementById('v2ConfirmRenewal').click();await h.done;const c=h.get().credits.at(-1);a.deepEqual(c.schedule.map(x=>x.amount),[180,180,180,180]);a.equal(c.total,720)}finally{h.close()}
});
test('an additional installment that consumes the total cannot advance or register a renewal',async()=>{
 const h=await open();try{const before=JSON.stringify(h.get());h.set('v2RenewExtraAmount','720');h.set('v2RenewExtraDate','2026-11-06');h.w.document.getElementById('v2RenewReview').click();a.equal(h.w.document.getElementById('v2RenewalReview'),null);a.match(h.alerts.at(-1),/EXTRA_PAYMENTS_EXCEED_TOTAL/);a.equal(JSON.stringify(h.get()),before);a.equal(h.commits.length,0);h.w.document.getElementById('v2RenewCancel').click();await h.done}finally{h.close()}
});
