const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
function setup(){const output=[],gradient={addColorStop(){}},ctx=new Proxy({fillText:(text,x,y)=>output.push({text:String(text),x,y}),measureText:text=>({width:String(text).length*9}),createLinearGradient:()=>gradient},{get:(o,k)=>o[k]||(()=>{})}),canvases=[],w={document:{createElement:()=>{const cv={getContext:()=>ctx,toBlob:fn=>fn({type:'image/png'})};canvases.push(cv);return cv}}};w.window=w;vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../app/share-card-renderer-v2.js'),'utf8'),w);return {api:w.MiCarteraV2ShareCard,output,canvases}}
const client={name:'Cliente visual ficticio',phone:'999111333'},schedule=Array.from({length:4},(_,i)=>({number:i+1,amount:100,balance:100,date:`2026-10-${String(2+i*7).padStart(2,'0')}`})).concat({number:'A1',extra:true,amount:320,balance:320,date:'2026-10-30'}),credit={capital:600,total:720,rate:20,term:4,freq:'weekly',firstPaymentDate:'2026-10-02',schedule};
test('every customer image uses the common compact brand frame and preserves its financial facts',async()=>{for(const [kind,args,title,facts] of [
 ['proposal',[{...credit,kind:'credit',first:'2026-10-02',installment:100},client],'PROPUESTA DE CRÉDITO',['S/ 600.00','S/ 720.00','20%']],
 ['proposal',[{...credit,kind:'renewal',first:'2026-10-02',installment:100,previousBalance:240,netDisbursement:360},client],'PROPUESTA DE RENOVACIÓN',['S/ 240.00','S/ 360.00','30/10/2026']],
 ['credit',[credit,client],'DETALLE DEL CRÉDITO',['S/ 600.00','S/ 720.00','PENDIENTE','S/ 320.00']],
 ['receipt',[{amount:50,date:'2026-10-02',concept:'CUOTA',installmentNumber:1},client,credit],'COMPROBANTE DE PAGO',['S/ 50.00','2/10/2026','CUOTA 1 DE 5']],
 ['reminder',[{amount:100,date:'2026-10-30'},client],'RECORDATORIO DE PAGO',['S/ 100.00','30/10/2026','PENDIENTE']]
 ]){const h=setup(),before=JSON.stringify(args);await h.api[kind](...args);const texts=h.output.map(x=>x.text);for(const t of ['PRÉSTAMO YA','Tus metas, más cerca',title,client.name,'¡Gracias por confiar en nosotros!'])a.ok(texts.includes(t),`${kind}: ${t}`);for(const t of facts)a.ok(texts.includes(t),`${kind}: ${t}`);a.equal(h.canvases[0].width,720);a.ok(h.output.every(x=>x.x>=18&&x.x<=702&&x.y>0&&x.y<h.canvases[0].height));a.equal(JSON.stringify(args),before)}});
test('the complete credit schedule retains individual pending balances and ends at zero remaining balance',async()=>{const h=setup();await h.api.credit(credit,client);const date=h.output.find(x=>x.text==='30/10/2026');a.ok(date);a.ok(h.output.some(x=>x.y===date.y&&x.text==='S/ 320.00'));a.ok(h.output.some(x=>x.y===date.y&&x.text==='S/ 0.00'));a.ok(h.output.some(x=>x.text.includes('4 cuotas semanales')));a.ok(h.output.some(x=>x.text.includes('5.ª cuota adicional')));a.equal(h.api.creditTotals(credit).balance,720)});
test('long credit schedules grow vertically and never silently drop future or additional installments',async()=>{const h=setup(),long={...credit,term:12,total:1200,schedule:Array.from({length:12},(_,i)=>({number:i+1,date:`2027-${String(i+1).padStart(2,'0')}-02`,amount:100,balance:100}))};await h.api.credit(long,client);a.ok(h.output.some(x=>x.text==='2/12/2027'));a.ok(h.canvases[0].height>1080);a.ok(h.output.every(x=>x.y<h.canvases[0].height))});
