const assert=require('assert'),fs=require('fs'),path=require('path');
const app=path.join(__dirname,'../app');
const shell=fs.readFileSync(path.join(app,'operational-shell.html'),'utf8');
const controller=fs.readFileSync(path.join(app,'operational-controller.js'),'utf8');
const proposal=fs.readFileSync(path.join(app,'proposal-share-v2.js'),'utf8');
const credit=fs.readFileSync(path.join(app,'credit-detail-share-v2.js'),'utf8');
const receipt=fs.readFileSync(path.join(app,'payment-receipt-v2.js'),'utf8');
const renderer=fs.readFileSync(path.join(app,'share-card-renderer-v2.js'),'utf8');
const reminder=fs.readFileSync(path.join(app,'collection-reminder-share-v2.js'),'utf8');
const agenda=fs.readFileSync(path.join(app,'agenda-v2.js'),'utf8');
const cx=fs.readFileSync(path.join(app,'customer-experience-v2.js'),'utf8');
const sw=fs.readFileSync(path.join(app,'service-worker.js'),'utf8');
const release=JSON.parse(fs.readFileSync(path.join(app,'release.json'),'utf8'));
const workerBuild=(sw.match(/const BUILD='([^']+)'/)||[])[1];
assert.ok(workerBuild,'service worker build missing');
assert.strictEqual(release.build,workerBuild,'release.json and service-worker.js builds must match');
assert.ok(shell.includes('💬 Compartir propuesta'),'credit proposal share action missing');
assert.ok(shell.includes('share-card-renderer-v2.js'),'canonical share renderer not loaded');
assert.ok(shell.indexOf('share-card-renderer-v2.js')<shell.indexOf('credit-detail-share-v2.js'),'renderer must load before credit detail sharing');
assert.ok(shell.includes('credit-detail-share-v2.js'),'credit detail share module not loaded');
assert.ok(shell.includes('payment-receipt-v2.js'),'payment receipt share module not loaded');
assert.ok(controller.includes('💬 Compartir comprobante'),'payment history receipt action missing');
assert.ok(controller.includes('V2UI.sharePaymentReceipt'),'payment history receipt action not wired');
assert.ok(controller.includes('MiCarteraV2PaymentReceipt.share'),'payment receipt module not invoked from history');
assert.ok(controller.includes("state.payments.find(x=>x.id===paymentId)"),'receipt must resolve the selected payment');
assert.ok(proposal.includes('navigator.share'),'proposal native share missing');
assert.ok(proposal.includes("return 'file-share'"),'proposal branded file share missing');
assert.ok(!proposal.includes('MiCarteraV2CustomerExperience.whatsapp')&&!proposal.includes('navigator.clipboard?.writeText'),'proposal must not degrade to text-only sharing');
assert.ok(proposal.includes('El crédito NO queda registrado'),'proposal mutation warning missing');
assert.ok(credit.includes('navigator.share'),'credit detail native share missing');
assert.ok(credit.includes("return 'file-share'"),'credit detail branded file share missing');
assert.ok(!credit.includes('MiCarteraV2CustomerExperience.whatsapp')&&!credit.includes('navigator.clipboard?.writeText'),'credit detail must not degrade to text-only sharing');
assert.ok(credit.includes('status(q)'),'credit detail text must render installment status');
assert.ok(renderer.includes("txt(x,'Estado',690,700"),'credit image schedule status column missing');
assert.ok(renderer.includes('installmentStatus(q)'),'credit image must calculate installment status');
assert.ok(renderer.includes("canvas('RECORDATORIO DE PAGO'"),'canonical renderer must provide reminder card');
assert.ok(renderer.includes("metric(x,'Cuota pendiente'"),'reminder card must use the structured branded summary');
assert.ok(renderer.includes("txt(x,'Detalle del pago'"),'reminder card must show a structured payment detail section');
assert.ok(renderer.includes("metric(x,'Estado',state"),'reminder card must show the payment state');
assert.ok(receipt.includes('COMPROBANTE DE PAGO'),'payment receipt title missing');
assert.ok(receipt.includes('navigator.share'),'payment receipt native share missing');
assert.ok(receipt.includes("return 'file-share'"),'payment receipt branded file share missing');
assert.ok(!receipt.includes('MiCarteraV2CustomerExperience.whatsapp')&&!receipt.includes('navigator.clipboard?.writeText'),'payment receipt must not degrade to text-only sharing');
assert.ok(receipt.includes('Pago confirmado.'),'payment receipt confirmation missing');
assert.ok(!receipt.includes('Operación: ${p?.id')&&!receipt.includes('Crédito: ${cr?.id'),'customer receipt text must not expose internal ids');
assert.ok(!renderer.includes("metric(x,'Crédito',cr?.id")&&!renderer.includes("metric(x,'Operación',p?.id"),'customer receipt image must not expose internal ids');
assert.ok(cx.includes('https://wa.me/'),'central WhatsApp transport missing');
assert.ok(agenda.includes('MiCarteraV2CollectionReminderShare.share'),'agenda must invoke unified reminder sharing');
assert.ok(agenda.includes('📤 Compartir recordatorio'),'agenda must expose reminder share action');
assert.ok(reminder.includes('navigator.share'),'reminder native share missing');
assert.ok(reminder.includes("if(blob){try{const file=new File"),'reminder must attempt branded image regardless of phone availability');
assert.ok(!reminder.includes('if(blob&&!hasPhone)'),'reminder must not bypass branded image merely because client has a phone');
assert.ok(reminder.includes('MiCarteraV2CustomerExperience?.whatsapp'),'reminder WhatsApp fallback missing');
assert.ok(reminder.includes('navigator.clipboard?.writeText'),'reminder clipboard fallback missing');
assert.ok(reminder.includes("console.warn('V2 reminder clipboard fallback failed.'"),'reminder clipboard rejection must be handled');
assert.ok(reminder.includes("throw new Error(hasPhone?'REMINDER_SHARE_UNAVAILABLE':'REMINDER_SHARE_UNAVAILABLE_NO_PHONE')"),'reminder clipboard failure must end in controlled error');
assert.ok(reminder.includes('REMINDER_SHARE_UNAVAILABLE_NO_PHONE'),'reminder no-phone fallback must remain explicit');
for(const file of ['./proposal-share-v2.js','./credit-detail-share-v2.js','./payment-receipt-v2.js','./customer-experience-v2.js','./agenda-v2.js','./share-card-renderer-v2.js','./collection-reminder-share-v2.js'])assert.ok(sw.includes(file),`offline sharing shell missing ${file}`);
console.log('V2 customer sharing experience: PASS');

assert.ok(preview.includes('editableMessage:true'),'payment preview must expose editable suggested message');
assert.ok(preview.includes('Mensaje sugerido (puedes editarlo)'),'editable payment message label missing');
assert.ok(receipt.includes('editedMessage'),'payment share must accept edited message');
assert.ok(receipt.includes('text:msg,files:[file]'),'payment share must send edited message with branded image');
assert.ok(renderer.includes('Tus pagos puntuales nos ayudan a mantener tu crédito disponible'),'approved punctuality message missing from receipt image');
