const {test}=require('node:test'),a=require('node:assert/strict'),{planVerifiedRecovery}=require('../migration/verified-journal-recovery.cjs');
const copy=x=>JSON.parse(JSON.stringify(x));
function fixture(){const current={ 'routes/leader-cash-revision':{id:'leader-cash-revision',recordType:'LEADER_CASH_REVISION',version:1},'credits/fake-credit':{id:'fake-credit',clientId:'fake-client',status:'ACTIVO',version:2,capital:100,total:120,principalPaid:20,interestPaid:4,penaltyPaid:0,schedule:[{amount:120,paid:24,balance:96}]}},operation={id:'fake-op',actorId:'fake-admin',type:'PAYMENT',writes:[{kind:'set',path:'credits/fake-credit',expectedVersion:2,data:{...current['credits/fake-credit'],version:3,principalPaid:30,interestPaid:6,schedule:[{amount:120,paid:36,balance:84}]}},{kind:'create',path:'payments/fake-pay',expectedVersion:0,data:{id:'fake-pay',clientId:'fake-client',creditId:'fake-credit',date:'2026-10-02',amount:12,capitalAmount:10,interestAmount:2,penaltyAmount:0,version:1}},{kind:'create',path:'entries/fake-cash',expectedVersion:0,data:{id:'fake-cash',ref:'fake-pay',type:'INGRESO',amount:12,date:'2026-10-02',version:1}},{kind:'create',path:'routes/leader-cash-revision',expectedVersion:0,data:{id:'leader-cash-revision',recordType:'LEADER_CASH_REVISION',version:1}},{kind:'create',path:'audit/fake-audit',expectedVersion:0,data:{id:'fake-audit',actorId:'fake-admin',operationId:'fake-op',action:'PAYMENT_RECORDED'}}]};return {current,operation,options:{actorId:'fake-admin',sourceSha256:'a'.repeat(64),now:'2026-10-03T12:00:00Z',expectedCashGuard:1}}}
test('verified recovery adjusts only the shared cash revision and preserves the source operation and fingerprint',()=>{const f=fixture(),before=JSON.stringify(f),p=planVerifiedRecovery(f.operation,f.current,f.options);a.equal(p.status,'READY');a.equal(JSON.stringify(f),before);a.equal(p.writes.find(w=>w.path==='routes/leader-cash-revision').data.version,2);a.equal(p.writes.find(w=>w.path==='credits/fake-credit').data.principalPaid,30);a.equal(p.record.fingerprint,require('../core/transaction-store.js').fingerprint(f.operation));a.equal(p.record.recovery.operationUnchanged,true);a.equal(p.writes.length,5)});
test('already-applied journal record produces zero writes and cannot duplicate cash',()=>{const f=fixture(),p=planVerifiedRecovery(f.operation,f.current,f.options);f.current['operations/fake-op']=p.record;const second=planVerifiedRecovery(f.operation,f.current,f.options);a.equal(second.status,'ALREADY_APPLIED');a.deepEqual(second.writes,[])});
test('recovery refuses fingerprint collision, changed credit, partial existing records and another actor',()=>{for(const mutate of [f=>f.current['operations/fake-op']={id:'fake-op',status:'APPLIED',actorId:'fake-admin',type:'PAYMENT',fingerprint:'wrong'},f=>f.current['credits/fake-credit'].version++,f=>f.current['payments/fake-pay']=copy(f.operation.writes[1].data),f=>f.options.actorId='another']){const f=fixture();mutate(f);a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options))}});
test('recovery refuses a semantic duplicate with a different ID and stale cash snapshot',()=>{const f=fixture();f.current['payments/another-id']={...f.operation.writes[1].data,id:'another-id'};a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/DUPLICATE/);delete f.current['payments/another-id'];f.options.expectedCashGuard=0;a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/CASH_SNAPSHOT/)});
test('recovery refuses missing cash revision and unsupported or malformed journal writes',()=>{for(const mutate of [f=>delete f.current['routes/leader-cash-revision'],f=>f.operation.type='WORKER_FUNDED',f=>f.operation.writes.push({kind:'set',path:'members/fake-admin',data:{role:'admin'}}),f=>f.operation.writes[1].data.amount=13]){const f=fixture();mutate(f);a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options))}});
function refinance(){const f=fixture(),old=f.current['credits/fake-credit'],fresh={id:'fake-renewal',clientId:'fake-client',renewedFrom:old.id,originDebt:96,capital:150,total:180,netDisbursement:54,date:'2026-10-02',principalPaid:0,interestPaid:0,version:1,schedule:[{amount:180,paid:0,balance:180}]};f.operation.type='REFINANCE';f.operation.writes=[{kind:'set',path:'credits/fake-credit',expectedVersion:2,data:{...old,version:3,status:'RENOVADO',renewedTo:fresh.id,renewedAt:fresh.date}},{kind:'create',path:'credits/fake-renewal',expectedVersion:0,data:fresh},{kind:'create',path:'expenses/fake-out',expectedVersion:0,data:{id:'fake-out',ref:fresh.id,date:fresh.date,type:'EGRESO',amount:54,version:1}},f.operation.writes[3],f.operation.writes[4]];return f}
function cash(){const f=fixture();f.operation.type='CASH_MOVEMENT';f.operation.writes=[{kind:'create',path:'expenses/fake-out',expectedVersion:0,data:{id:'fake-out',date:'2026-10-02',type:'EGRESO',amount:24,category:'OTROS_GASTOS',concept:'Gasto ficticio',version:1}},f.operation.writes[3],f.operation.writes[4]];return f}
test('verified refinance preserves the old payment history and original dates/net amounts',()=>{const f=refinance(),before=copy(f.current['credits/fake-credit']),p=planVerifiedRecovery(f.operation,f.current,f.options);a.equal(p.writes.find(w=>w.path==='expenses/fake-out').data.amount,54);a.equal(p.writes.find(w=>w.path==='credits/fake-renewal').data.date,'2026-10-02');a.deepEqual(p.writes.find(w=>w.path==='credits/fake-credit').data.schedule,before.schedule);a.equal(before.version,2)});
test('verified cash recovery preserves the original expense and blocks a semantic duplicate',()=>{const f=cash(),p=planVerifiedRecovery(f.operation,f.current,f.options);a.equal(p.writes.find(w=>w.path==='expenses/fake-out').data.amount,24);f.current['expenses/different-id']={...f.operation.writes[0].data,id:'different-id'};a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/DUPLICATE/)});
test('refinance recovery blocks an existing successor or changed original schedule',()=>{const f=refinance();f.current['credits/other-successor']={id:'other-successor',renewedFrom:'fake-credit'};a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/DUPLICATE/);delete f.current['credits/other-successor'];f.operation.writes[0].data.schedule=[{amount:120,paid:0,balance:120}];a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/SOURCE_CONTENT/)});
test('payment recovery rejects a dangling duplicate cash receipt under a different ID',()=>{const f=fixture();f.current['entries/other-cash-id']={...f.operation.writes[2].data,id:'other-cash-id'};a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/DUPLICATE/)});
test('payment recovery rejects a schedule that clears more debt than the original payment',()=>{const f=fixture();f.operation.writes[0].data.schedule=[{amount:120,paid:120,balance:0}];a.throws(()=>planVerifiedRecovery(f.operation,f.current,f.options),/SCHEDULE/)});
