// Mi Cartera PRO V2 — safe operational sync boundary. No Firebase globals, no polling.
(function(root,factory){const api=factory(root);if(typeof module==='object'&&module.exports)module.exports=api;else root.MiCarteraV2OperationalSync=api;})(typeof globalThis!=='undefined'?globalThis:this,function(root){'use strict';
function sid(v){return String(v??'').trim()}function clone(v){return JSON.parse(JSON.stringify(v))}
function createOperationalSync(cfg){const store=cfg?.store;if(!store||typeof store.execute!=='function')throw new Error('V2_STORE_REQUIRED');const queue=cfg?.queue||null;const actorId=sid(cfg?.actorId||'v2-user');const state={status:'IDLE',lastFlushAt:null,lastError:null};
 function operation(input){if(!input?.operationId)throw new Error('OPERATION_ID_REQUIRED');const writes=[];for(const x of input.entities||[]){if(!x?.collection||!x?.data?.id)throw new Error('SYNC_ENTITY_INVALID');const data=clone(x.data);const expected=x.kind==='create'?0:Number(data.version||0)-1;writes.push({kind:x.kind||'set',path:`${x.collection}/${data.id}`,data,expectedVersion:expected});}if(input.audit?.id)writes.push({kind:'create',path:`audit/${input.audit.id}`,data:clone(input.audit),expectedVersion:0});return {id:sid(input.operationId),operationId:sid(input.operationId),type:sid(input.type||'OPERATIONAL'),createdAt:input.createdAt||new Date().toISOString(),actorId,writes};}
 async function submit(input){const op=operation(input);try{return await store.execute(op)}catch(error){if(queue&&typeof queue.enqueue==='function'){const code=String(error?.code||error?.message||'');if(/RESOURCE_EXHAUSTED|UNAVAILABLE|NETWORK|OFFLINE|TIMEOUT/i.test(code)){queue.enqueue(op);state.status='PENDING';state.lastError=code;return {status:'QUEUED',operationId:op.operationId,error:code};}}throw error;}}
 async function flush(){if(!queue||typeof queue.flush!=='function')return {status:'NO_QUEUE'};state.status='SYNCING';try{const result=await queue.flush(op=>store.execute(op));state.status='SYNCED';state.lastFlushAt=new Date().toISOString();state.lastError=null;return result}catch(error){state.status='ERROR';state.lastError=String(error?.code||error?.message||error||'SYNC_FAILED');throw error;}}
 function emit(name,detail){if(typeof root?.dispatchEvent!=='function')return;try{const E=typeof root.CustomEvent==='function'?root.CustomEvent:null;if(E)root.dispatchEvent(new E(name,{detail}));}catch(_){}}
 function reconnect(){if(typeof root?.addEventListener!=='function'||!queue||typeof queue.flush!=='function')return false;root.addEventListener('online',async()=>{try{const result=await flush();emit('mi-cartera-v2-sync',{ok:true,result,state:getState()});}catch(error){emit('mi-cartera-v2-sync',{ok:false,error:state.lastError,state:getState()});}});return true}
 function getState(){return clone(state)}
 reconnect();return {operation,submit,flush,getState};}
return {createOperationalSync};});