from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
for old,new in [('Mi Cartera PRO V21 Cloud','Préstamo Ya'),('Mi Cartera PRO','Préstamo Ya'),('mi-cartera-backup-','prestamo-ya-backup-')]:
    s=s.replace(old,new)

if 'manifest.webmanifest' not in s:
    s=s.replace('</head>','<link rel="manifest" href="manifest.webmanifest"><link rel="icon" href="icon.svg" type="image/svg+xml"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><meta name="apple-mobile-web-app-title" content="Préstamo Ya"><link rel="apple-touch-icon" href="icon.svg"></head>',1)
anchor='<button class="btn" id="cloudUserBtn" onclick="openCloudLogin()">☁️ Entrar</button>'
if 'openBackupPanel()' not in s:
    s=s.replace(anchor,'<button class="btn" onclick="openBackupPanel()">💾 Respaldo</button>'+anchor,1)
if 'src="backup.js"' not in s:
    s=s.replace('</body>','<script src="backup.js"></script><script>if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));}</script></body>',1)
p.write_text(s,encoding='utf-8')

Path('manifest.webmanifest').write_text('''{"name":"Préstamo Ya","short_name":"Préstamo Ya","description":"Gestión de clientes, créditos, cobranza, caja y cartera.","start_url":"./","scope":"./","display":"standalone","orientation":"portrait","background_color":"#f4f6f7","theme_color":"#78c7ef","icons":[{"src":"icon.svg","sizes":"any","type":"image/svg+xml","purpose":"any maskable"}]}''',encoding='utf-8')

Path('backup.js').write_text('''(function(){function safeDb(){try{return typeof db!=="undefined"?db:null}catch(e){return null}}function openBackupPanel(){const old=document.getElementById("backupPanel");if(old){old.remove();return}const d=document.createElement("div");d.id="backupPanel";d.className="modal open";d.innerHTML='<div class="sheet"><button class="btn close" onclick="document.getElementById(\\'backupPanel\\').remove()">✕</button><div class="sectionTitle">Respaldo y recuperación</div><p class="small muted">Exporta tu información y restáurala en otro dispositivo.</p><div class="card"><b>Guardar respaldo</b><p class="small">Clientes, créditos, pagos, caja, rutas, usuarios y configuración.</p><button class="btn green wide" onclick="exportCarteraBackup()">⬇️ Descargar respaldo</button></div><div class="card"><b>Recuperar respaldo</b><input id="backupFile" type="file" accept="application/json,.json" class="input" style="margin-bottom:8px"><button class="btn blue wide" onclick="importCarteraBackup()">⬆️ Restaurar respaldo</button></div><div class="card"><b>Importante</b><div class="small">La recuperación automática entre dispositivos llegará con la cuenta Cloud y la base de datos central.</div></div></div>';document.body.appendChild(d)}function exportCarteraBackup(){const d=safeDb();if(!d)return toast("No se pudo leer la información");const payload={app:"Préstamo Ya",version:21,exportedAt:new Date().toISOString(),db:d};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="prestamo-ya-backup-"+(typeof today==='function'?today():new Date().toISOString().slice(0,10))+".json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast("Respaldo descargado correctamente")}function importCarteraBackup(){const input=document.getElementById("backupFile"),file=input&&input.files&&input.files[0];if(!file)return toast("Selecciona un respaldo .json");const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(r.result);if(!p||!p.db||!Array.isArray(p.db.clients)||!Array.isArray(p.db.credits)||!Array.isArray(p.db.payments))throw new Error();if(!confirm("Esto reemplazará los datos locales actuales. ¿Continuar?"))return;localStorage.setItem("miCarteraDB",JSON.stringify(p.db));location.reload()}catch(e){toast("Respaldo inválido o dañado")}};r.readAsText(file)}window.openBackupPanel=openBackupPanel;window.exportCarteraBackup=exportCarteraBackup;window.importCarteraBackup=importCarteraBackup})();''',encoding='utf-8')